//! Shared `wasm-opt` post-pass for emitted wasm-gc core modules.
//!
//! Both `aver compile --target wasm-gc --optimize ...` and the in-memory
//! `aver run --wasm-gc --optimize ...` path call this module. Keeping the
//! proposal flags here is important: an artifact accepted by one path must
//! not be rejected only because the other drifted onto a different command.

use std::path::Path;

/// User-facing optimization goal for an emitted wasm-gc core module.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OptimizationMode {
    /// Binaryen `-O3`: prioritize steady-state execution speed.
    Speed,
    /// Binaryen `-Oz`: prioritize the smallest delivered module.
    Size,
}

impl OptimizationMode {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Speed => "speed",
            Self::Size => "size",
        }
    }

    const fn wasm_opt_flag(self) -> &'static str {
        match self {
            Self::Speed => "-O3",
            Self::Size => "-Oz",
        }
    }
}

/// Byte sizes observed around one successful optimization pass.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OptimizationReport {
    pub input_size: u64,
    pub output_size: u64,
}

/// Optimize an artifact in place with Binaryen.
pub fn optimize_artifact(
    wasm_file: &Path,
    mode: OptimizationMode,
) -> Result<OptimizationReport, String> {
    let input_size = std::fs::metadata(wasm_file)
        .map(|meta| meta.len())
        .map_err(|e| format!("Failed to stat {}: {}", wasm_file.display(), e))?;
    let stage1_file = wasm_file.with_extension("dce.wasm");
    let optimized_file = wasm_file.with_extension("opt.wasm");
    let opt_flag = mode.wasm_opt_flag();

    std::fs::copy(wasm_file, &stage1_file)
        .map_err(|e| format!("Failed to stage wasm for opt: {}", e))?;

    // Fixed-point optimization plus metadata stripping. Both public callers
    // intentionally use this exact proposal set.
    let output = std::process::Command::new("wasm-opt")
        .arg(opt_flag)
        .arg("--converge")
        .arg("--strip-producers")
        .arg("--strip-target-features")
        .arg("--enable-bulk-memory")
        .arg("--enable-multivalue")
        .arg("--enable-tail-call")
        .arg("--enable-gc")
        .arg("--enable-reference-types")
        // The bignum f64->Int helper emits `i64.trunc_sat_f64_u`; stripping
        // target-features means Binaryen must receive the proposal explicitly.
        .arg("--enable-nontrapping-float-to-int")
        .arg(&stage1_file)
        .arg("-o")
        .arg(&optimized_file)
        .output()
        .map_err(|e| {
            let _ = std::fs::remove_file(&stage1_file);
            format!(
                "Failed to run wasm-opt {} for {}: {}. Install binaryen or omit --optimize.",
                opt_flag,
                wasm_file.display(),
                e
            )
        })?;

    let _ = std::fs::remove_file(&stage1_file);

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let _ = std::fs::remove_file(&optimized_file);
        return Err(format!(
            "wasm-opt {} failed for {}: {}",
            opt_flag,
            wasm_file.display(),
            stderr.trim()
        ));
    }

    std::fs::rename(&optimized_file, wasm_file).map_err(|e| {
        format!(
            "Failed to replace {} with wasm-opt output: {}",
            wasm_file.display(),
            e
        )
    })?;

    let output_size = std::fs::metadata(wasm_file)
        .map(|meta| meta.len())
        .map_err(|e| format!("Failed to stat optimized {}: {}", wasm_file.display(), e))?;
    Ok(OptimizationReport {
        input_size,
        output_size,
    })
}

/// Optimize generated bytes for an in-process consumer such as Wasmtime.
pub fn optimize_bytes(bytes: &[u8], mode: OptimizationMode) -> Result<Vec<u8>, String> {
    let directory = tempfile::Builder::new()
        .prefix("aver-wasm-gc-")
        .tempdir()
        .map_err(|e| format!("Failed to create temporary wasm artifact: {e}"))?;
    let wasm_file = directory.path().join("input.wasm");
    std::fs::write(&wasm_file, bytes)
        .map_err(|e| format!("Failed to stage generated wasm bytes: {e}"))?;

    optimize_artifact(&wasm_file, mode)?;
    std::fs::read(&wasm_file).map_err(|e| format!("Failed to read optimized wasm bytes: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn optimization_modes_keep_cli_labels_and_binaryen_flags_together() {
        assert_eq!(OptimizationMode::Speed.label(), "speed");
        assert_eq!(OptimizationMode::Speed.wasm_opt_flag(), "-O3");
        assert_eq!(OptimizationMode::Size.label(), "size");
        assert_eq!(OptimizationMode::Size.wasm_opt_flag(), "-Oz");
    }
}
