//! Freshness gate for the generated agent artifacts.
//!
//! `tools/website/llms.txt`, `tools/website/llms-full.txt`, and `docs/cli.md`
//! are generated by `tools/website/build_llms.sh` from two hand-written
//! sources (`.claude/commands/aver.md`, `.claude/commands/aver-tooling.md`)
//! plus the three website intro/outro fragments. All three generated files are
//! committed: the website serves them, README links them, and `aver
//! agent-connect --print` `include_str!`s `llms.txt` straight into the binary.
//! A source edit that skips the regeneration therefore ships a binary whose
//! guide disagrees with the repository.
//!
//! The gate regenerates into a temporary tree — a copy of only the inputs the
//! script reads — and byte-compares. The worktree is never written to.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Everything `build_llms.sh` reads, as paths relative to the repository root.
const SCRIPT_INPUTS: &[&str] = &[
    "tools/website/build_llms.sh",
    "tools/website/llms_intro.md",
    "tools/website/llms_outro.md",
    "tools/website/llms_full_intro.md",
    ".claude/commands/aver.md",
    ".claude/commands/aver-tooling.md",
];

/// Everything it writes, as paths relative to the repository root.
const SCRIPT_OUTPUTS: &[&str] = &[
    "tools/website/llms.txt",
    "tools/website/llms-full.txt",
    "docs/cli.md",
];

fn bash_is_available() -> bool {
    Command::new("bash")
        .arg("-c")
        .arg("exit 0")
        .output()
        .is_ok_and(|output| output.status.success())
}

fn copy_into(root: &Path, relative: &str) {
    let source = repo_root().join(relative);
    let destination = root.join(relative);
    fs::create_dir_all(destination.parent().expect("input has a parent directory"))
        .expect("create input directory in the temporary tree");
    fs::copy(&source, &destination)
        .unwrap_or_else(|error| panic!("copy {relative} into the temporary tree: {error}"));
}

#[test]
fn committed_llms_artifacts_match_a_fresh_build() {
    if !bash_is_available() {
        eprintln!(
            "skipping the llms freshness gate — no usable `bash` on PATH, and \
             tools/website/build_llms.sh is a bash script"
        );
        return;
    }

    let temp = tempfile::tempdir().expect("temporary tree");
    let root = temp.path();
    for input in SCRIPT_INPUTS {
        copy_into(root, input);
    }
    // `build_llms.sh` redirects into docs/cli.md without creating the directory.
    fs::create_dir_all(root.join("docs")).expect("create docs directory");

    let build = Command::new("bash")
        .arg(root.join("tools/website/build_llms.sh"))
        .output()
        .expect("expected `bash tools/website/build_llms.sh` to spawn");
    assert!(
        build.status.success(),
        "regenerating the llms artifacts failed:\nstatus: {}\nstdout:\n{}\nstderr:\n{}",
        build.status,
        String::from_utf8_lossy(&build.stdout),
        String::from_utf8_lossy(&build.stderr)
    );

    for output in SCRIPT_OUTPUTS {
        let fresh = fs::read(root.join(output))
            .unwrap_or_else(|error| panic!("read the freshly built {output}: {error}"));
        let committed = fs::read(repo_root().join(output))
            .unwrap_or_else(|error| panic!("read the committed {output}: {error}"));

        assert_eq!(
            String::from_utf8_lossy(&committed),
            String::from_utf8_lossy(&fresh),
            "{output} is stale: it does not match a fresh build from \
             .claude/commands/aver.md and .claude/commands/aver-tooling.md. \
             Run `tools/website/build_llms.sh` and commit the result."
        );
    }
}

#[test]
fn the_bundled_language_guide_is_the_committed_one() {
    // `aver agent-connect --print` emits `include_str!`-ed bytes. Reading the
    // same file here keeps the gate above load-bearing for the binary: if
    // llms.txt is stale, what the binary prints is stale too.
    let committed = fs::read_to_string(repo_root().join("tools/website/llms.txt"))
        .expect("read the committed llms.txt");

    assert!(committed.starts_with("# Aver\n"));
    assert!(
        committed.contains("### Decision blocks"),
        "the curated guide must document `decision` blocks"
    );
}
