//! WIT emission for the component artifact.
//!
//! Per the component contract (`docs/wasip2.md` point 5), every
//! `.component.wasm` we emit ships a sibling `.wit` whose contents
//! are the human-readable view of the import / export surface.
//!
//! Phase 1 transitional: emits an empty world in the `aver:user`
//! package. The wasm-gc core's `_start` and any internal exports
//! become private to the component (not surfaced through the world).
//! Phase 1.2+ extends this to `include wasi:cli/command;` once WASI
//! WIT bundles are wired into the binary; per-effect imports beyond
//! the upstream WASI worlds (rare — most effects map cleanly) are
//! composed via `wit-encoder` from there.

use super::wrap::Wasip2World;

/// Emit the WIT source that pairs with the component bytes. The
/// emitted source is also parsed by `wrap.rs` to build the
/// `component-type:<world>` metadata custom section, so this is the
/// single source of truth for what the component declares.
///
/// Phase 1 keeps the world body empty: Aver's effects do not yet
/// flow into WIT imports here. The wrap pipeline still validates
/// end-to-end on the empty world (component is a valid WASI 0.2
/// artifact, just with no public surface). Phase 1.2 turns this
/// into a meaningful world declaration.
pub fn emit_world_wit(world: Wasip2World) -> String {
    let local_name = world.local_name();
    let upstream_note = match world {
        Wasip2World::CliCommand => "// Phase 1.2+ will replace this body with `include wasi:cli/command;`",
        Wasip2World::HttpProxy => "// Phase 3 / 0.19 work. Compile-rejected in 0.18.",
    };
    format!(
        "// Generated by `aver compile --target wasip2`.\n\
         // Direct WIT lowering: this is the source of truth for the\n\
         // component's import / export surface. Component metadata is\n\
         // encoded from this same WIT and embedded into the core\n\
         // module. See docs/wasip2.md for the contract.\n\
         //\n\
         {upstream_note}\n\n\
         package aver:user;\n\n\
         world {local_name} {{\n\
         }}\n"
    )
}
