//! WIT emission for the component artifact.
//!
//! Per the component contract (`docs/wasip2.md` point 5), every
//! `.component.wasm` we emit ships a sibling `.wit` whose contents
//! are the human-readable view of the import / export surface.
//!
//! Phase 1 emits a minimal world declaration that re-exports the
//! upstream `wasi:cli/command` / `wasi:http/proxy` worlds. As
//! later phases add per-effect imports beyond the standard worlds
//! (rare — most effects map cleanly to the standard WASI 0.2 worlds),
//! this module grows to compose them via `wit-encoder`.

use super::wrap::Wasip2World;

/// Emit the WIT source that pairs with the component bytes. Static
/// for now — composes `aver:user/<world>` whose body re-includes the
/// upstream WASI world. The `wit-encoder` crate would let us build
/// this programmatically once Phase 1.2+ adds custom imports beyond
/// the WASI surface (no current need; deferred).
pub fn emit_world_wit(world: Wasip2World) -> String {
    let upstream = world.wit_name();
    let local_name = match world {
        Wasip2World::CliCommand => "command",
        Wasip2World::HttpProxy => "http-proxy",
    };
    format!(
        "// Generated by `aver compile --target wasip2`.\n\
         // Re-exports the upstream WASI world; per-effect imports are\n\
         // satisfied by the component-model host (wasmtime, Spin, etc.).\n\
         //\n\
         // See docs/wasip2.md for the contract this artifact obeys.\n\n\
         package aver:user;\n\n\
         world {local_name} {{\n\
         \x20\x20include {upstream};\n\
         }}\n"
    )
}
