/// Lean 4 backend for the Aver transpiler.
///
/// Transpiles only pure core logic: functions without effects, type definitions,
/// verify blocks (as `example ... := by sorry`), and decision blocks (as comments).
/// Effectful functions and `main` are skipped.
mod builtins;
mod expr;
mod pattern;
mod shared;
mod toplevel;
mod types;

use std::collections::HashSet;

use crate::ast::{FnDef, TopLevel};
use crate::call_graph;
use crate::codegen::{CodegenContext, ProjectOutput};

/// Transpile an Aver program to a Lean 4 project.
pub fn transpile(ctx: &CodegenContext) -> ProjectOutput {
    let mut sections = Vec::new();

    // Prelude
    sections.push(generate_prelude());
    sections.push(String::new());

    // Detect recursive functions for `partial` annotation
    let recursive_fns = call_graph::find_recursive_fns(&ctx.items);

    // Module type definitions (from depends)
    for module in &ctx.modules {
        for td in &module.type_defs {
            sections.push(toplevel::emit_type_def(td));
            // #18: Recursive types need unsafe DecidableEq instance
            if toplevel::is_recursive_type_def(td) {
                sections.push(toplevel::emit_recursive_decidable_eq(
                    toplevel::type_def_name(td),
                ));
            }
            sections.push(String::new());
        }
    }

    // Type definitions
    for td in &ctx.type_defs {
        sections.push(toplevel::emit_type_def(td));
        // #18: Recursive types need unsafe DecidableEq instance
        if toplevel::is_recursive_type_def(td) {
            sections.push(toplevel::emit_recursive_decidable_eq(
                toplevel::type_def_name(td),
            ));
        }
        sections.push(String::new());
    }

    // Emit pure functions in SCC-topological order:
    // callees first, then callers; SCCs as `mutual` blocks.
    emit_pure_functions(ctx, &recursive_fns, &mut sections);

    // Decision blocks (as comments)
    for item in &ctx.items {
        if let TopLevel::Decision(db) = item {
            sections.push(toplevel::emit_decision(db));
            sections.push(String::new());
        }
    }

    // Verify blocks → example ... := by sorry
    for item in &ctx.items {
        if let TopLevel::Verify(vb) = item {
            sections.push(toplevel::emit_verify_block(vb, ctx));
            sections.push(String::new());
        }
    }

    let lean_source = sections.join("\n");

    // Project files
    let project_name = capitalize_first(&ctx.project_name);
    let lakefile = generate_lakefile(&project_name);
    let toolchain = generate_toolchain();

    ProjectOutput {
        files: vec![
            ("lakefile.lean".to_string(), lakefile),
            ("lean-toolchain".to_string(), toolchain),
            (format!("{}.lean", project_name), lean_source),
        ],
    }
}

fn emit_pure_functions(
    ctx: &CodegenContext,
    recursive_fns: &HashSet<String>,
    sections: &mut Vec<String>,
) {
    let all_fns: Vec<&FnDef> = ctx
        .modules
        .iter()
        .flat_map(|m| m.fn_defs.iter())
        .chain(ctx.fn_defs.iter())
        .filter(|fd| toplevel::is_pure_fn(fd))
        .collect();
    if all_fns.is_empty() {
        return;
    }

    let components = call_graph::ordered_fn_components(&all_fns);
    for fns in components {
        if fns.is_empty() {
            continue;
        }

        // Multi-node SCC => emit `mutual ... end`.
        if fns.len() > 1 {
            sections.push(toplevel::emit_mutual_group(&fns, ctx));
            sections.push(String::new());
            continue;
        }

        // Singleton SCC => regular `def` (recursive singletons still get `partial`
        // via `recursive_fns` in emit_fn_def).
        if let Some(code) = toplevel::emit_fn_def(fns[0], recursive_fns, ctx) {
            sections.push(code);
            sections.push(String::new());
        }
    }
}

fn generate_prelude() -> String {
    let mut lines = Vec::new();
    lines.push("-- Generated by the Aver → Lean 4 transpiler".to_string());
    lines.push("-- Pure core logic only (effectful functions are omitted)".to_string());
    lines.push(String::new());
    lines.push("-- Prelude: helper definitions for Aver builtins".to_string());
    lines.push(String::new());

    // #2: Int → Float coercion
    lines.push("instance : Coe Int Float := ⟨fun n => Float.ofInt n⟩".to_string());
    lines.push(String::new());

    // #6: Float DecidableEq (Float is opaque in Lean kernel)
    // unsafe + @[implemented_by] pattern: computable, native_decide works, deriving works
    lines.push(
        "private unsafe def Float.unsafeDecEq (a b : Float) : Decidable (a = b) :=".to_string(),
    );
    lines.push("  if a == b then isTrue (unsafeCast ()) else isFalse (unsafeCast ())".to_string());
    lines.push("@[implemented_by Float.unsafeDecEq]".to_string());
    lines.push("private opaque Float.compDecEq (a b : Float) : Decidable (a = b)".to_string());
    lines.push("instance : DecidableEq Float := Float.compDecEq".to_string());
    lines.push(String::new());

    // #7: Except DecidableEq
    lines.push("instance [DecidableEq ε] [DecidableEq α] : DecidableEq (Except ε α)".to_string());
    lines.push("  | .ok a, .ok b =>".to_string());
    lines.push(
        "    if h : a = b then isTrue (h ▸ rfl) else isFalse (by intro h'; cases h'; exact h rfl)"
            .to_string(),
    );
    lines.push("  | .error a, .error b =>".to_string());
    lines.push(
        "    if h : a = b then isTrue (h ▸ rfl) else isFalse (by intro h'; cases h'; exact h rfl)"
            .to_string(),
    );
    lines.push("  | .ok _, .error _ => isFalse (by intro h; cases h)".to_string());
    lines.push("  | .error _, .ok _ => isFalse (by intro h; cases h)".to_string());
    lines.push(String::new());

    // Except.withDefault
    lines.push("namespace Except".to_string());
    lines.push("def withDefault (r : Except ε α) (d : α) : α :=".to_string());
    lines.push("  match r with".to_string());
    lines.push("  | .ok v => v".to_string());
    lines.push("  | .error _ => d".to_string());
    lines.push("end Except".to_string());
    lines.push(String::new());

    // Option.toExcept
    lines.push("def Option.toExcept (o : Option α) (e : ε) : Except ε α :=".to_string());
    lines.push("  match o with".to_string());
    lines.push("  | some v => .ok v".to_string());
    lines.push("  | none => .error e".to_string());
    lines.push(String::new());

    // #13: String + → String.append (Lean uses ++ not +)
    lines.push("instance : HAdd String String String := ⟨String.append⟩".to_string());
    lines.push(String::new());

    // Map helpers (Map<K,V> = List (K × V))
    lines.push("namespace AverMap".to_string());
    lines.push("def empty : List (α × β) := []".to_string());
    lines.push("def get [BEq α] (m : List (α × β)) (k : α) : Option β :=".to_string());
    lines.push("  match m with".to_string());
    lines.push("  | [] => none".to_string());
    lines.push("  | (k', v) :: rest => if k == k' then some v else AverMap.get rest k".to_string());
    lines.push("def set [BEq α] (m : List (α × β)) (k : α) (v : β) : List (α × β) :=".to_string());
    lines.push("  let rec go : List (α × β) → List (α × β)".to_string());
    lines.push("    | [] => [(k, v)]".to_string());
    lines.push(
        "    | (k', v') :: rest => if k == k' then (k, v) :: rest else (k', v') :: go rest"
            .to_string(),
    );
    lines.push("  go m".to_string());
    lines.push("def has [BEq α] (m : List (α × β)) (k : α) : Bool :=".to_string());
    lines.push("  m.any (fun p => p.1 == k)".to_string());
    lines.push("def remove [BEq α] (m : List (α × β)) (k : α) : List (α × β) :=".to_string());
    lines.push("  m.filter (fun p => !(p.1 == k))".to_string());
    lines.push("def keys (m : List (α × β)) : List α := m.map Prod.fst".to_string());
    lines.push("def values (m : List (α × β)) : List β := m.map Prod.snd".to_string());
    lines.push("def entries (m : List (α × β)) : List (α × β) := m".to_string());
    lines.push("def len (m : List (α × β)) : Nat := m.length".to_string());
    lines.push("def fromList (entries : List (α × β)) : List (α × β) := entries".to_string());
    lines.push("end AverMap".to_string());
    lines.push(String::new());

    lines.push("namespace AverList".to_string());
    lines.push("private def insertSorted [Ord α] (x : α) : List α → List α".to_string());
    lines.push("  | [] => [x]".to_string());
    lines.push("  | y :: ys =>".to_string());
    lines.push("    if compare x y == Ordering.lt || compare x y == Ordering.eq then".to_string());
    lines.push("      x :: y :: ys".to_string());
    lines.push("    else".to_string());
    lines.push("      y :: insertSorted x ys".to_string());
    lines.push("def sort [Ord α] (xs : List α) : List α :=".to_string());
    lines.push("  xs.foldl (fun acc x => insertSorted x acc) []".to_string());
    lines.push("end AverList".to_string());
    lines.push(String::new());

    // String helpers (Aver has no Char type — single chars are strings)
    // charAt/slice are code-point based to match interpreter semantics.
    lines.push("def String.charAt (s : String) (i : Int) : Option String :=".to_string());
    lines.push("  if i < 0 then none".to_string());
    lines.push("  else (s.toList.get? i.toNat).map Char.toString".to_string());
    lines.push("def String.slice (s : String) (start stop : Int) : String :=".to_string());
    lines.push("  let startN := if start < 0 then 0 else start.toNat".to_string());
    lines.push("  let stopN := if stop < 0 then 0 else stop.toNat".to_string());
    lines.push("  let chars := s.toList".to_string());
    lines.push("  String.mk ((chars.drop startN).take (stopN - startN))".to_string());
    lines.push("def String.fromInt (n : Int) : String := toString n".to_string());
    lines.push("def String.fromFloat (f : Float) : String := toString f".to_string());
    lines.push(
        "def String.chars (s : String) : List String := s.toList.map Char.toString".to_string(),
    );
    lines.push("namespace AverString".to_string());
    lines.push("def split (s delim : String) : List String :=".to_string());
    lines.push("  if delim.isEmpty then".to_string());
    lines.push("    \"\" :: (s.toList.map Char.toString) ++ [\"\"]".to_string());
    lines.push("  else".to_string());
    lines.push("    s.splitOn delim".to_string());
    lines.push("end AverString".to_string());
    lines.push(String::new());

    // Int/Float parsing (Aver returns Result<T, String>)
    lines.push("def Int.fromString (s : String) : Except String Int :=".to_string());
    lines.push("  match s.toInt? with".to_string());
    lines.push("  | some n => .ok n".to_string());
    lines.push("  | none => .error (\"Invalid integer: \" ++ s)".to_string());
    lines.push(String::new());

    // #19: Float.fromString — real parser using Float.ofScientific
    lines.push("private def charDigitsToNat (cs : List Char) : Nat :=".to_string());
    lines.push("  cs.foldl (fun acc c => acc * 10 + (c.toNat - '0'.toNat)) 0".to_string());
    lines.push(String::new());
    lines.push("private def parseExpPart : List Char → (Bool × List Char)".to_string());
    lines.push("  | '-' :: rest => (true, rest.takeWhile Char.isDigit)".to_string());
    lines.push("  | '+' :: rest => (false, rest.takeWhile Char.isDigit)".to_string());
    lines.push("  | rest => (false, rest.takeWhile Char.isDigit)".to_string());
    lines.push(String::new());
    lines.push("def Float.fromString (s : String) : Except String Float :=".to_string());
    lines.push("  let chars := s.toList".to_string());
    lines.push("  let (neg, chars) := match chars with".to_string());
    lines.push("    | '-' :: rest => (true, rest)".to_string());
    lines.push("    | _ => (false, chars)".to_string());
    lines.push("  let intPart := chars.takeWhile Char.isDigit".to_string());
    lines.push("  let rest := chars.dropWhile Char.isDigit".to_string());
    lines.push("  let (fracPart, rest) := match rest with".to_string());
    lines.push(
        "    | '.' :: rest => (rest.takeWhile Char.isDigit, rest.dropWhile Char.isDigit)"
            .to_string(),
    );
    lines.push("    | _ => ([], rest)".to_string());
    lines.push("  let (expNeg, expDigits) := match rest with".to_string());
    lines.push("    | 'e' :: rest => parseExpPart rest".to_string());
    lines.push("    | 'E' :: rest => parseExpPart rest".to_string());
    lines.push("    | _ => (false, [])".to_string());
    lines.push(
        "  if intPart.isEmpty && fracPart.isEmpty then .error (\"Invalid float: \" ++ s)"
            .to_string(),
    );
    lines.push("  else".to_string());
    lines.push("    let mantissa := charDigitsToNat (intPart ++ fracPart)".to_string());
    lines.push("    let fracLen : Int := fracPart.length".to_string());
    lines.push("    let expVal : Int := charDigitsToNat expDigits".to_string());
    lines.push("    let shift : Int := (if expNeg then -expVal else expVal) - fracLen".to_string());
    lines.push(
        "    let f := if shift >= 0 then Float.ofScientific mantissa false shift.toNat".to_string(),
    );
    lines.push("             else Float.ofScientific mantissa true ((-shift).toNat)".to_string());
    lines.push("    .ok (if neg then -f else f)".to_string());
    lines.push(String::new());

    // Char helpers (Aver Char namespace operates on strings)
    lines.push("def Char.toCode (s : String) : Int :=".to_string());
    lines.push("  match s.toList.head? with".to_string());
    lines.push("  | some c => (c.toNat : Int)".to_string());
    lines.push("  | none => panic! \"Char.toCode: string is empty\"".to_string());
    lines.push("def Char.fromCode (n : Int) : Option String :=".to_string());
    lines.push("  if n < 0 then none".to_string());
    lines.push("  else some (Char.toString (Char.ofNat n.toNat))".to_string());
    lines.push(String::new());

    // #20: Hex conversion helpers (for Byte.toHex / Byte.fromHex)
    lines.push("def hexDigit (n : Int) : String :=".to_string());
    lines.push("  match n with".to_string());
    lines.push("  | 0 => \"0\" | 1 => \"1\" | 2 => \"2\" | 3 => \"3\"".to_string());
    lines.push("  | 4 => \"4\" | 5 => \"5\" | 6 => \"6\" | 7 => \"7\"".to_string());
    lines.push("  | 8 => \"8\" | 9 => \"9\" | 10 => \"a\" | 11 => \"b\"".to_string());
    lines.push("  | 12 => \"c\" | 13 => \"d\" | 14 => \"e\" | 15 => \"f\"".to_string());
    lines.push("  | _ => \"?\"".to_string());
    lines.push(String::new());
    lines.push("def byteToHex (code : Int) : String :=".to_string());
    lines.push("  hexDigit (code / 16) ++ hexDigit (code % 16)".to_string());
    lines.push(String::new());
    lines.push("namespace AverByte".to_string());
    lines.push("private def hexValue (c : Char) : Option Int :=".to_string());
    lines.push("  match c with".to_string());
    lines.push("  | '0' => some 0  | '1' => some 1  | '2' => some 2  | '3' => some 3".to_string());
    lines.push("  | '4' => some 4  | '5' => some 5  | '6' => some 6  | '7' => some 7".to_string());
    lines.push("  | '8' => some 8  | '9' => some 9  | 'a' => some 10 | 'b' => some 11".to_string());
    lines.push("  | 'c' => some 12 | 'd' => some 13 | 'e' => some 14 | 'f' => some 15".to_string());
    lines.push("  | 'A' => some 10 | 'B' => some 11 | 'C' => some 12 | 'D' => some 13".to_string());
    lines.push("  | 'E' => some 14 | 'F' => some 15".to_string());
    lines.push("  | _ => none".to_string());
    lines.push("def toHex (n : Int) : Except String String :=".to_string());
    lines.push("  if n < 0 || n > 255 then".to_string());
    lines.push(
        "    .error (\"Byte.toHex: \" ++ toString n ++ \" is out of range 0-255\")".to_string(),
    );
    lines.push("  else".to_string());
    lines.push("    .ok (byteToHex n)".to_string());
    lines.push("def fromHex (s : String) : Except String Int :=".to_string());
    lines.push("  match s.toList with".to_string());
    lines.push("  | [hi, lo] =>".to_string());
    lines.push("    match hexValue hi, hexValue lo with".to_string());
    lines.push("    | some h, some l => .ok (h * 16 + l)".to_string());
    lines.push("    | _, _ => .error (\"Byte.fromHex: invalid hex '\" ++ s ++ \"'\")".to_string());
    lines.push(
        "  | _ => .error (\"Byte.fromHex: expected exactly 2 hex chars, got '\" ++ s ++ \"'\")"
            .to_string(),
    );
    lines.push("end AverByte".to_string());

    lines.join("\n")
}

fn generate_lakefile(project_name: &str) -> String {
    format!(
        r#"import Lake
open Lake DSL

package «{}» where
  version := v!"0.1.0"

@[default_target]
lean_lib «{}» where
  srcDir := "."
"#,
        project_name.to_lowercase(),
        project_name
    )
}

fn generate_toolchain() -> String {
    "leanprover/lean4:v4.15.0\n".to_string()
}

fn capitalize_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}
