// Generated by `aver compile --pack cloudflare` — bootstrap that
// satisfies user.wasm's `aver_runtime.*` and `aver/*` imports inside
// the Cloudflare Workers JS environment. Edit freely; regenerating
// will overwrite this file.

import userWasm from "./__WASM_NAME__.wasm";

// The Aver runtime module (alloc, GC, HAMT, string/list/vector ops)
// is shared across every program — load it once from the published
// CDN. Pin to a specific version for reproducible deploys.
const RUNTIME_URL = "https://averlang.dev/runtime/latest/aver_runtime.wasm";
let runtimeInstance = null;
let runtimeMemory = null;

async function loadRuntime() {
  if (runtimeInstance) return runtimeInstance;
  const res = await fetch(RUNTIME_URL);
  const bytes = await res.arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes, {});
  runtimeInstance = instance;
  runtimeMemory = instance.exports.memory;
  return instance;
}

// Per-request state the fetch-bridge host imports read and write.
// Reset before each `aver_http_handle` invocation.
let pending = null;

function writeAverString(memory, alloc, encoder, text) {
  // Build an OBJ_STRING in guest memory: 8-byte header + UTF-8
  // bytes. Header low 32 bits = byte length; kind=0 (OBJ_STRING)
  // is the high byte and is naturally zero. Returns the ptr that
  // the guest treats as a String.
  const bytes = encoder.encode(text);
  const ptr = alloc(bytes.length + 8);
  const view = new DataView(memory.buffer);
  view.setBigUint64(ptr, BigInt(bytes.length), true);
  new Uint8Array(memory.buffer, ptr + 8, bytes.length).set(bytes);
  return ptr;
}

function makeAverImports() {
  const decoder = new TextDecoder("utf-8");
  const encoder = new TextEncoder();
  const readString = (ptr, len) =>
    decoder.decode(new Uint8Array(runtimeMemory.buffer, ptr, len));
  // Lazy alloc helper — uses the guest-exported `alloc` symbol so
  // String objects we hand back are first-class on the heap.
  const alloc = (size) => {
    if (!userInstancePromise) {
      throw new Error("alloc called before user.wasm instantiated");
    }
    // `userInstancePromise` resolves before host imports fire,
    // but TS-style we still grab it lazily.
    return globalThis.__aver_alloc(size);
  };

  return {
    console_print: (ptr, len) => console.log(readString(ptr, len)),
    console_error: (ptr, len) => console.error(readString(ptr, len)),
    console_warn:  (ptr, len) => console.warn(readString(ptr, len)),
    time_unixMs:   () => BigInt(Date.now()),
    random_int: (lo, hi) => {
      const span = hi - lo + 1n;
      return lo + BigInt(Math.floor(Math.random() * Number(span)));
    },
    random_float: () => Math.random(),
    // ─── Fetch bridge: HTTP request fields & response builder ────
    // Each host import is a lazy crossing — guest pays only for
    // the fields it reads.
    request_method: () => writeAverString(
      runtimeMemory, alloc, encoder, pending?.req?.method ?? "GET",
    ),
    request_url: () => writeAverString(
      runtimeMemory, alloc, encoder,
      pending?.req ? new URL(pending.req.url).pathname : "/",
    ),
    request_body: () => {
      // body() is sync from Aver's POV; if we already buffered it
      // we hand back the OBJ_STRING, else empty. Bootstrap pre-reads
      // the body before invoking the handler.
      return writeAverString(runtimeMemory, alloc, encoder, pending?.body ?? "");
    },
    response_text: (status, ptr, len) => {
      // Stash response data; native Response built post-handler. The
      // headers list is populated by `response_set_header` calls
      // emitted in the HttpResponse construction lowering — those
      // fire before this finalizer so they're already on the pending
      // record by the time we land here.
      const existingHeaders = pending.response?.headers ?? [];
      pending.response = {
        status,
        body: readString(ptr, len),
        headers: existingHeaders,
      };
      // Return a non-zero sentinel so user code that checks the
      // handle for truthiness is happy.
      return 1;
    },
    response_set_header: (namePtr, nameLen, valuePtr, valueLen) => {
      // Append `(name, value)` to the pending Response's headers.
      // We push individual pairs (rather than a Map) so multi-value
      // headers — Set-Cookie, Vary, … — preserve order and don't
      // collide.
      if (!pending.response) pending.response = { headers: [] };
      if (!pending.response.headers) pending.response.headers = [];
      pending.response.headers.push([
        readString(namePtr, nameLen),
        readString(valuePtr, valueLen),
      ]);
    },
    // ─── Print/Format value ─────────────────────────────────────
    // The compiler imports these unconditionally: `print_value`
    // backs `Console.print(non-string)` and the format-debug paths,
    // `format_value` backs string interpolation when an argument
    // isn't already a String (it returns the (ptr, len) of an
    // OBJ_STRING describing the value). Stub bodies just route
    // primitives to their natural string forms; richer formatting
    // (records, lists with shape) is on the host runtime to expand.
    print_value: (tag, val) => console.log(formatValueForHost(tag, val)),
    format_value: (tag, val) => {
      const text = formatValueForHost(tag, val);
      const ptr = writeAverString(runtimeMemory, alloc, encoder, text);
      // Two-result return — fetch-bridge ABI declares (ptr, len).
      // The OBJ_STRING handle's bytes start at ptr+8; the i32 length
      // lives in the header low 32 bits.
      const view = new DataView(runtimeMemory.buffer);
      const len = Number(view.getBigUint64(ptr, true) & 0xffffffffn);
      return [ptr + 8, len];
    },
  };
}

// Tag values follow Aver's runtime convention:
//   0 = Int (i64 raw bits in `val`)
//   1 = Float (f64 reinterpreted from `val`)
//   2 = Bool (i32 in low bits)
//   3 = String (OBJ_STRING ptr in low 32 bits — read length + bytes)
//   4 = Heap (record/list/etc. — render generic placeholder for now)
function formatValueForHost(tag, val) {
  switch (tag) {
    case 0: return String(val);            // Int
    case 1: {
      // Float — i64 bits → f64
      const buf = new ArrayBuffer(8);
      new BigInt64Array(buf)[0] = val;
      return String(new Float64Array(buf)[0]);
    }
    case 2: return Number(val) ? "true" : "false";
    case 3: {
      const ptr = Number(val & 0xffffffffn);
      if (ptr === 0) return "";
      const view = new DataView(runtimeMemory.buffer);
      const len = Number(view.getBigUint64(ptr, true) & 0xffffffffn);
      return new TextDecoder("utf-8").decode(
        new Uint8Array(runtimeMemory.buffer, ptr + 8, len),
      );
    }
    default: return "<heap>";
  }
}

async function instantiateUser() {
  const runtime = await loadRuntime();
  const imports = {
    aver_runtime: runtime.exports,
    aver: makeAverImports(),
  };
  // Wrangler's `CompiledWasm` import gives a `WebAssembly.Module`,
  // not raw bytes — `WebAssembly.instantiate(module, imports)`
  // returns the `Instance` directly (not `{instance, module}`).
  const instance = await WebAssembly.instantiate(userWasm, imports);
  // Host imports allocate OBJ_STRING handles via the guest-exported
  // `alloc` symbol (the runtime's bump allocator). Stash it in a
  // global so request_* / response_* imports can reach it without
  // threading a closure through every call.
  globalThis.__aver_alloc = instance.exports.alloc;
  return instance;
}

let userInstancePromise = null;

export default {
  async fetch(request, env, ctx) {
    if (!userInstancePromise) userInstancePromise = instantiateUser();
    const user = await userInstancePromise;

    // If --handler was passed, the user's HTTP handler is exported
    // as `aver_http_handle`. We pre-read the body, stash request
    // state, invoke the handler, then build a native Response from
    // whatever the handler stashed via `response_text`.
    if (typeof user.exports.aver_http_handle === "function") {
      const body = await request.text();
      pending = { req: request, body, response: null };
      try {
        user.exports.aver_http_handle(0);
      } catch (e) {
        console.error("aver_http_handle threw:", e);
        pending = null;
        return new Response("Internal error\n", { status: 500 });
      }
      const resp = pending.response;
      pending = null;
      if (!resp) {
        return new Response(
          "Handler returned without calling Response builder\n",
          { status: 500 },
        );
      }
      // Build the native Headers from the (name, value) pairs the
      // guest produced. Web Fetch `Headers.append` is multi-value
      // safe — duplicate Set-Cookie entries stay distinct, comma-
      // joined headers are emitted as separate appends so the host
      // can decide whether to fold (per RFC 9110 §5.3 it can; for
      // Set-Cookie per RFC 6265 it shouldn't).
      const headers = new Headers();
      for (const [name, value] of resp.headers ?? []) {
        headers.append(name, value);
      }
      // Default content-type only when the guest didn't set one.
      if (!headers.has("content-type")) {
        headers.set("content-type", "text/plain;charset=utf-8");
      }
      return new Response(resp.body, { status: resp.status, headers });
    }

    // No --handler: run _start once for side-effect output, return
    // a placeholder response. Useful for "Hello from Aver" demos
    // that just want to prove the toolchain works.
    if (typeof user.exports._start === "function") {
      user.exports._start();
    } else if (typeof user.exports.main === "function") {
      user.exports.main();
    }
    return new Response("Aver program ran. Output went to wrangler logs.\n", {
      headers: { "content-type": "text/plain;charset=utf-8" },
    });
  },
};
