// Generated by `aver compile --pack cloudflare` — bootstrap that
// satisfies user.wasm's `aver_runtime.*` and `aver/*` imports inside
// the Cloudflare Workers JS environment. Edit freely; regenerating
// will overwrite this file.

import userWasm from "./__WASM_NAME__.wasm";

// The Aver runtime module (alloc, GC, HAMT, string/list/vector ops)
// is shared across every program — load it once from the published
// CDN. Pin to a specific version for reproducible deploys.
const RUNTIME_URL = "https://averlang.dev/runtime/latest/aver_runtime.wasm";
let runtimeInstance = null;
let runtimeMemory = null;

async function loadRuntime() {
  if (runtimeInstance) return runtimeInstance;
  const res = await fetch(RUNTIME_URL);
  const bytes = await res.arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes, {});
  runtimeInstance = instance;
  runtimeMemory = instance.exports.memory;
  // Expose the runtime exports at module scope so host-side
  // header builders can call `rt_map_from_list` directly when
  // bulk-transferring `Request.headers` / `Response.headers`.
  runtimeExports = instance.exports;
  return instance;
}

// Per-request state the fetch-bridge host imports read and write.
// Reset before each `aver_http_handle` invocation.
let pending = null;

function writeAverString(memory, alloc, encoder, text) {
  // Build an OBJ_STRING in guest memory: 8-byte header + UTF-8
  // bytes. Header low 32 bits = byte length; kind=0 (OBJ_STRING)
  // is the high byte and is naturally zero. Returns the ptr that
  // the guest treats as a String.
  const bytes = encoder.encode(text);
  const ptr = alloc(bytes.length + 8);
  const view = new DataView(memory.buffer);
  view.setBigUint64(ptr, BigInt(bytes.length), true);
  new Uint8Array(memory.buffer, ptr + 8, bytes.length).set(bytes);
  return ptr;
}

function makeAverImports() {
  const decoder = new TextDecoder("utf-8");
  // Expose `readString` / `alloc` / `encoder` at module scope so
  // the JSPI-suspending `http_send` (constructed lazily, outside
  // this closure) can decode and allocate without re-deriving the
  // helpers. The module-level placeholders get replaced here.
  readString = (ptr, len) =>
    decoder.decode(new Uint8Array(runtimeMemory.buffer, ptr, len));
  alloc = (size) => {
    if (!userInstancePromise) {
      throw new Error("alloc called before user.wasm instantiated");
    }
    // `userInstancePromise` resolves before host imports fire,
    // but TS-style we still grab it lazily.
    return globalThis.__aver_alloc(size);
  };

  return {
    console_print: (ptr, len) => console.log(readString(ptr, len)),
    console_error: (ptr, len) => console.error(readString(ptr, len)),
    console_warn:  (ptr, len) => console.warn(readString(ptr, len)),
    time_unixMs:   () => BigInt(Date.now()),
    random_int: (lo, hi) => {
      const span = hi - lo + 1n;
      return lo + BigInt(Math.floor(Math.random() * Number(span)));
    },
    random_float: () => Math.random(),
    // ─── Fetch bridge: HTTP request fields & response builder ────
    // Each host import is a lazy crossing — guest pays only for
    // the fields it reads.
    request_method: () => writeAverString(
      runtimeMemory, alloc, encoder, pending?.req?.method ?? "GET",
    ),
    request_url: () => writeAverString(
      runtimeMemory, alloc, encoder,
      pending?.req ? new URL(pending.req.url).pathname : "/",
    ),
    request_body: () => {
      // body() is sync from Aver's POV; if we already buffered it
      // we hand back the OBJ_STRING, else empty. Bootstrap pre-reads
      // the body before invoking the handler.
      return writeAverString(runtimeMemory, alloc, encoder, pending?.body ?? "");
    },
    request_headers_load: () => {
      const h = pending?.req?.headers;
      if (!h) return 0;
      return buildHeadersMap(h);
    },
    response_text: (status, ptr, len) => {
      // Stash response data; native Response built post-handler. The
      // headers list is populated by `response_set_header` calls
      // emitted in the HttpResponse construction lowering — those
      // fire before this finalizer so they're already on the pending
      // record by the time we land here.
      const existingHeaders = pending.response?.headers ?? [];
      pending.response = {
        status,
        body: readString(ptr, len),
        headers: existingHeaders,
      };
      // Return a non-zero sentinel so user code that checks the
      // handle for truthiness is happy.
      return 1;
    },
    response_set_header: (namePtr, nameLen, valuePtr, valueLen) => {
      // Append `(name, value)` to the pending Response's headers.
      // We push individual pairs (rather than a Map) so multi-value
      // headers — Set-Cookie, Vary, … — preserve order and don't
      // collide.
      if (!pending.response) pending.response = { headers: [] };
      if (!pending.response.headers) pending.response.headers = [];
      pending.response.headers.push([
        readString(namePtr, nameLen),
        readString(valuePtr, valueLen),
      ]);
    },
    // ─── Env ───────────────────────────────────────────────
    // Workers' `env` is the bag of bindings + secrets passed to
    // `fetch(request, env, ctx)`. We stash it on `pending.env` for
    // the duration of the handler call (see the fetch entrypoint
    // below). Returns -1 (Aver's NONE_SENTINEL) when the name
    // isn't bound, otherwise allocates a guest OBJ_STRING.
    env_get: (namePtr, nameLen) => {
      const name = readString(namePtr, nameLen);
      const value = pending?.env?.[name];
      if (typeof value !== "string") return -1;
      return writeAverString(runtimeMemory, alloc, encoder, value);
    },
    // Workers `env` is read-only — `env_set` is a no-op so the
    // typed contract `Env.set: (String, String) -> Unit` still
    // holds without lying about persistence.
    env_set: (_namePtr, _nameLen, _valuePtr, _valueLen) => {},
    // ─── Http (client) ──────────────────────────────────────
    // `Http.<verb>(...)` is a synchronous-looking wasm call that
    // really has to `await fetch(...)` on the host. We bridge the
    // sync↔async gap with the JS Promise Integration (JSPI)
    // proposal: each suspending import is wrapped via
    // `WebAssembly.Suspending(asyncFn)` (see `instantiateUser`),
    // and the exported handler is wrapped with
    // `WebAssembly.promising(wasmFn)` so a top-level `await`
    // chains the suspension all the way back to the worker's
    // `fetch` entrypoint.
    //
    // Browser, Workers, Deno, Bun all ship V8 / SpiderMonkey
    // builds with JSPI enabled; if you target a runtime that
    // doesn't have it, replace these with synchronous stubs that
    // return a transport error.
    //
    // Request headers travel over a host-maintained pending list:
    //   `http_clear_request_headers` resets it before each call,
    //   `http_add_request_header(name, value)` appends an entry
    //    (multi-value friendly via repeated calls),
    //   `http_send(method, url, body, contentType)` consumes the
    //    pending list, executes the fetch, returns
    //    `(status, body, err)`.
    http_clear_request_headers: () => {
      pending.requestHeaders = [];
    },
    http_add_request_header: (namePtr, nameLen, valuePtr, valueLen) => {
      if (!pending.requestHeaders) pending.requestHeaders = [];
      pending.requestHeaders.push([
        readString(namePtr, nameLen),
        readString(valuePtr, valueLen),
      ]);
    },
    http_send: makeSuspendingHttpSend(),
    // ─── Print/Format value ─────────────────────────────────────
    // The compiler imports these unconditionally: `print_value`
    // backs `Console.print(non-string)` and the format-debug paths,
    // `format_value` backs string interpolation when an argument
    // isn't already a String (it returns the (ptr, len) of an
    // OBJ_STRING describing the value). Stub bodies just route
    // primitives to their natural string forms; richer formatting
    // (records, lists with shape) is on the host runtime to expand.
    print_value: (tag, val) => console.log(formatValueForHost(tag, val)),
    format_value: (tag, val) => {
      const text = formatValueForHost(tag, val);
      const ptr = writeAverString(runtimeMemory, alloc, encoder, text);
      // Two-result return — fetch-bridge ABI declares (ptr, len).
      // The OBJ_STRING handle's bytes start at ptr+8; the i32 length
      // lives in the header low 32 bits.
      const view = new DataView(runtimeMemory.buffer);
      const len = Number(view.getBigUint64(ptr, true) & 0xffffffffn);
      return [ptr + 8, len];
    },
  };
}

// JSPI-suspending implementation of `aver/http_send`. The wasm
// guest calls this synchronously; control suspends here while we
// `await fetch(...)`, then resumes with the (status, body, err)
// triple on the wasm stack. `WebAssembly.Suspending` is supported
// out of the box in Cloudflare Workers / Deno / Bun / modern
// browsers; runtimes without JSPI should swap this for a sync
// stub that returns a transport error.
function makeSuspendingHttpSend() {
  if (typeof WebAssembly.Suspending !== "function") {
    // No JSPI — fall back to a sync stub that always reports a
    // transport failure. Programs branch on `Result.Err` instead
    // of crashing on a missing import.
    return (_m, _ml, _u, _ul, _b, _bl, _c, _cl) => {
      const err = writeAverString(
        runtimeMemory, alloc, encoder,
        "Http.send: host has no JSPI; cannot await fetch synchronously",
      );
      return [0n, 0, 0, err];
    };
  }
  return new WebAssembly.Suspending(async (
    methodPtr, methodLen, urlPtr, urlLen,
    bodyPtr, bodyLen, ctPtr, ctLen,
  ) => {
    const method = readString(methodPtr, methodLen);
    const url = readString(urlPtr, urlLen);
    const body = bodyLen > 0 ? readString(bodyPtr, bodyLen) : null;
    const contentType = ctLen > 0 ? readString(ctPtr, ctLen) : null;

    const init = { method };
    const headers = new Headers();
    if (contentType) headers.set("content-type", contentType);
    for (const [name, value] of pending.requestHeaders ?? []) {
      headers.append(name, value);
    }
    if ([...headers].length > 0) init.headers = headers;
    if (body !== null && method !== "GET" && method !== "HEAD") {
      init.body = body;
    }

    try {
      const resp = await fetch(url, init);
      const respBody = await resp.text();
      const bodyHandle = writeAverString(
        runtimeMemory, alloc, encoder, respBody,
      );
      // Bulk-transfer the upstream response headers into a guest
      // `Map<String, List<String>>` so Aver code can read
      // `resp.headers` (Content-Type, Set-Cookie, rate-limit
      // headers, ETag, …). Empty Map (`0`) when the upstream
      // sent nothing — same shape Aver code already handles.
      const headersHandle = buildHeadersMap(resp.headers);
      return [BigInt(resp.status), bodyHandle, headersHandle, 0];
    } catch (e) {
      const msg = e?.message ?? String(e);
      const errHandle = writeAverString(runtimeMemory, alloc, encoder, msg);
      return [0n, 0, 0, errHandle];
    }
  });
}

// `readString` / `alloc` / `encoder` live inside `makeAverImports`'s
// closure; pull module-level references so the JSPI-suspending
// `http_send` (constructed when `makeAverImports` runs) can use
// them at await-time without re-deriving the helpers. Initialized
// to safe no-ops; replaced when `makeAverImports` fires.
let readString = (_ptr, _len) => "";
let alloc = (_size) => 0;
let encoder = new TextEncoder();

// Reference to the loaded `aver_runtime` instance — populated by
// `loadRuntime` once the module is instantiated. Host-side header
// builders (`buildHeadersMap`) reach for `rt_map_from_list` here
// to materialize a HAMT root from a list of (name, [value, …])
// tuples without re-deriving the Map insertion logic.
let runtimeExports = null;

// Aver runtime kind tags / wrap codes the host needs when
// hand-building heap objects (OBJ_LIST_CONS for cons cells,
// OBJ_TUPLE for (name, values) entries). Mirrors
// `src/codegen/wasm/value.rs`.
const OBJ_LIST_CONS = 4n;
const OBJ_TUPLE = 7n;
const KIND_STR = 3;

// Build an `OBJ_LIST_CONS` cell at a fresh allocation. Layout
// matches `rt_list_cons` in the runtime: 8-byte header + 8-byte
// head value (i64) + 8-byte tail (i32 sign-extended into an i64
// slot).
function consCell(headValue, tail, headPtrFlag) {
  const ptr = alloc(24);
  const view = new DataView(runtimeMemory.buffer);
  // Header: kind << 56 | head_ptr_flag << 32 | field_count(2)
  const header =
    (OBJ_LIST_CONS << 56n) | (BigInt(headPtrFlag) << 32n) | 2n;
  view.setBigUint64(ptr, header, true);
  view.setBigUint64(ptr + 8, headValue, true);
  view.setBigInt64(ptr + 16, BigInt(tail | 0), true);
  return ptr;
}

// Build an `OBJ_TUPLE` of two heap pointers — used for the
// (name, values_list) entries that `rt_map_from_list` consumes.
function tupleStrList(namePtr, valuesListPtr) {
  const ptr = alloc(24);
  const view = new DataView(runtimeMemory.buffer);
  // Header: kind=OBJ_TUPLE | meta=0b11 (both fields are heap ptrs)
  // << 32 | field_count(2)
  const header = (OBJ_TUPLE << 56n) | (3n << 32n) | 2n;
  view.setBigUint64(ptr, header, true);
  view.setBigUint64(ptr + 8, BigInt(namePtr), true);
  view.setBigUint64(ptr + 16, BigInt(valuesListPtr), true);
  return ptr;
}

// Walk a JS `Headers` object and return a guest-side
// `Map<String, List<String>>` handle. Multi-value `Set-Cookie`
// uses `getSetCookie()` (Web Fetch API) so individual cookies
// land as separate list entries; everything else collapses
// into a single-element list (the Headers iterator already
// comma-joins same-name fields per RFC 9110 §5.3, which is the
// shape Aver code receives).
function buildHeadersMap(jsHeaders) {
  if (!runtimeExports || typeof runtimeExports.rt_map_from_list !== "function") {
    return 0;
  }
  let listTail = 0;

  // Set-Cookie first (if available) so the resulting Map sees
  // a real `["c1", "c2", …]` list under that name, not a
  // comma-collapsed single-element value.
  let cookies = [];
  if (typeof jsHeaders.getSetCookie === "function") {
    cookies = jsHeaders.getSetCookie();
  }
  if (cookies.length > 0) {
    let valueList = 0;
    for (let i = cookies.length - 1; i >= 0; i--) {
      const cookieStr = writeAverString(
        runtimeMemory, alloc, encoder, cookies[i],
      );
      valueList = consCell(BigInt(cookieStr), valueList, 1);
    }
    const nameStr = writeAverString(
      runtimeMemory, alloc, encoder, "set-cookie",
    );
    const tuple = tupleStrList(nameStr, valueList);
    listTail = consCell(BigInt(tuple), listTail, 1);
  }

  // Everything else — Headers iteration yields lowercase names
  // already, so we don't have to normalise. Skip Set-Cookie since
  // we handled it above (its iterator entries are also already
  // collapsed into one comma-joined string by spec, which is wrong
  // for Set-Cookie — `getSetCookie()` is the canonical reader).
  for (const [name, value] of jsHeaders) {
    if (name.toLowerCase() === "set-cookie") continue;
    const nameStr = writeAverString(runtimeMemory, alloc, encoder, name);
    const valueStr = writeAverString(runtimeMemory, alloc, encoder, value);
    const valueList = consCell(BigInt(valueStr), 0, 1);
    const tuple = tupleStrList(nameStr, valueList);
    listTail = consCell(BigInt(tuple), listTail, 1);
  }

  return runtimeExports.rt_map_from_list(listTail, KIND_STR, 1);
}

// Tag values follow Aver's runtime convention:
//   0 = Int (i64 raw bits in `val`)
//   1 = Float (f64 reinterpreted from `val`)
//   2 = Bool (i32 in low bits)
//   3 = String (OBJ_STRING ptr in low 32 bits — read length + bytes)
//   4 = Heap (record/list/etc. — render generic placeholder for now)
function formatValueForHost(tag, val) {
  switch (tag) {
    case 0: return String(val);            // Int
    case 1: {
      // Float — i64 bits → f64
      const buf = new ArrayBuffer(8);
      new BigInt64Array(buf)[0] = val;
      return String(new Float64Array(buf)[0]);
    }
    case 2: return Number(val) ? "true" : "false";
    case 3: {
      const ptr = Number(val & 0xffffffffn);
      if (ptr === 0) return "";
      const view = new DataView(runtimeMemory.buffer);
      const len = Number(view.getBigUint64(ptr, true) & 0xffffffffn);
      return new TextDecoder("utf-8").decode(
        new Uint8Array(runtimeMemory.buffer, ptr + 8, len),
      );
    }
    default: return "<heap>";
  }
}

async function instantiateUser() {
  const runtime = await loadRuntime();
  const imports = {
    aver_runtime: runtime.exports,
    aver: makeAverImports(),
  };
  // Wrangler's `CompiledWasm` import gives a `WebAssembly.Module`,
  // not raw bytes — `WebAssembly.instantiate(module, imports)`
  // returns the `Instance` directly (not `{instance, module}`).
  const instance = await WebAssembly.instantiate(userWasm, imports);
  // Host imports allocate OBJ_STRING handles via the guest-exported
  // `alloc` symbol (the runtime's bump allocator). Stash it in a
  // global so request_* / response_* imports can reach it without
  // threading a closure through every call.
  globalThis.__aver_alloc = instance.exports.alloc;

  // JSPI: when Http.* effects run, the wasm frame can suspend on
  // `await fetch(...)` inside `http_send`. To let the suspension
  // unwind back to a Promise, the entry the host calls must be
  // wrapped with `WebAssembly.promising`. We stash the wrapped
  // handler on a global so the worker's `fetch` entrypoint can
  // call `await averHandle(0)` instead of poking `instance.exports`
  // directly (its `aver_http_handle` slot is read-only).
  if (
    typeof instance.exports.aver_http_handle === "function" &&
    typeof WebAssembly.promising === "function"
  ) {
    globalThis.__aver_http_handle = WebAssembly.promising(
      instance.exports.aver_http_handle,
    );
  } else if (typeof instance.exports.aver_http_handle === "function") {
    // No JSPI on this host — call sync. Programs that hit Http.*
    // get a transport-error fallback from `makeSuspendingHttpSend`.
    globalThis.__aver_http_handle = instance.exports.aver_http_handle;
  }
  return instance;
}

let userInstancePromise = null;

export default {
  async fetch(request, env, ctx) {
    if (!userInstancePromise) userInstancePromise = instantiateUser();
    const user = await userInstancePromise;

    // If --handler was passed, the user's HTTP handler is exported
    // as `aver_http_handle`. We pre-read the body, stash request
    // state, invoke the handler, then build a native Response from
    // whatever the handler stashed via `response_text`.
    if (typeof user.exports.aver_http_handle === "function") {
      const body = await request.text();
      pending = { req: request, body, env, response: null, requestHeaders: [] };
      try {
        // `__aver_http_handle` is the JSPI-wrapped entry — `await`
        // it so any `Http.*` suspension chain resolves before we
        // build the Response. Falls back to a sync call when
        // JSPI isn't available (see `instantiateUser`).
        await globalThis.__aver_http_handle(0);
      } catch (e) {
        console.error("aver_http_handle threw:", e);
        pending = null;
        return new Response("Internal error\n", { status: 500 });
      }
      const resp = pending.response;
      pending = null;
      if (!resp) {
        return new Response(
          "Handler returned without calling Response builder\n",
          { status: 500 },
        );
      }
      // Build the native Headers from the (name, value) pairs the
      // guest produced. Web Fetch `Headers.append` is multi-value
      // safe — duplicate Set-Cookie entries stay distinct, comma-
      // joined headers are emitted as separate appends so the host
      // can decide whether to fold (per RFC 9110 §5.3 it can; for
      // Set-Cookie per RFC 6265 it shouldn't).
      const headers = new Headers();
      for (const [name, value] of resp.headers ?? []) {
        headers.append(name, value);
      }
      // Default content-type only when the guest didn't set one.
      if (!headers.has("content-type")) {
        headers.set("content-type", "text/plain;charset=utf-8");
      }
      return new Response(resp.body, { status: resp.status, headers });
    }

    // No --handler: run _start once for side-effect output, return
    // a placeholder response. Useful for "Hello from Aver" demos
    // that just want to prove the toolchain works.
    if (typeof user.exports._start === "function") {
      user.exports._start();
    } else if (typeof user.exports.main === "function") {
      user.exports.main();
    }
    return new Response("Aver program ran. Output went to wrangler logs.\n", {
      headers: { "content-type": "text/plain;charset=utf-8" },
    });
  },
};
