use aver::ast::{DecisionBlock, DecisionImpact, FnDef, TypeDef};
use aver::checker::expr_to_str;

use crate::context_data::FileContext;

const JSON_VERIFY_SAMPLE_LIMIT: usize = 3;
const VERIFY_SAMPLE_POLICY_ID: &str = "source_head_3";

fn impact_texts(impacts: &[DecisionImpact]) -> Vec<String> {
    impacts
        .iter()
        .map(DecisionImpact::as_context_string)
        .collect()
}

fn impact_json_texts(impacts: &[DecisionImpact]) -> Vec<String> {
    impacts
        .iter()
        .map(|impact| impact.text().to_string())
        .collect()
}

fn decision_ref_text(reference: &DecisionImpact) -> String {
    reference.as_context_string()
}

fn decision_ref_json_text(reference: &DecisionImpact) -> &str {
    reference.text()
}
const CONTEXT_SCHEMA_VERSION: u32 = 4;
const ANALYSIS_ENCODING_VERSION: u32 = 1;
const ANALYSIS_FLAG_AUTO_MEMO: u8 = 1;
const ANALYSIS_FLAG_AUTO_TCO: u8 = 2;
const MEMO_QUAL_PURE: u8 = 1;
const MEMO_QUAL_RECURSIVE: u8 = 2;
const MEMO_QUAL_SAFE_ARGS: u8 = 4;

fn memo_qual_mask(memo_qual: &[String]) -> u8 {
    let mut mask = 0u8;
    for q in memo_qual {
        match q.as_str() {
            "PURE" => mask |= MEMO_QUAL_PURE,
            "RECURSIVE" => mask |= MEMO_QUAL_RECURSIVE,
            "SAFE_ARGS" => mask |= MEMO_QUAL_SAFE_ARGS,
            _ => {}
        }
    }
    mask
}

pub(super) fn format_context_md(contexts: &[FileContext], entry_file: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Aver Context — {}\n\n", entry_file));
    out.push_str("_Generated by `aver context`_\n\n");

    let all_decisions: Vec<&DecisionBlock> =
        contexts.iter().flat_map(|c| c.decisions.iter()).collect();

    for ctx in contexts {
        let has_content =
            !ctx.fn_defs.is_empty() || !ctx.type_defs.is_empty() || !ctx.effect_sets.is_empty();

        if !has_content && ctx.module_name.is_none() {
            continue;
        }

        out.push_str("---\n\n");

        if let Some(name) = &ctx.module_name {
            out.push_str(&format!("## Module: {}\n\n", name));
        } else {
            out.push_str(&format!("## {}\n\n", ctx.source_file));
        }

        if let Some(intent) = &ctx.intent {
            out.push_str(&format!("> {}\n\n", intent));
        }

        out.push_str(&format!(
            "api_effects: `[{}]`  \n",
            ctx.api_effects.join(", ")
        ));
        out.push_str(&format!(
            "module_effects: `[{}]`  \n",
            ctx.module_effects.join(", ")
        ));
        if let Some(main_effects) = &ctx.main_effects {
            out.push_str(&format!(
                "main_effects: `[{}]`\n\n",
                main_effects.join(", ")
            ));
        } else {
            out.push_str("main_effects: `null`\n\n");
        }

        // Effect set aliases
        for (name, effects) in &ctx.effect_sets {
            out.push_str(&format!(
                "**effects** `{}` = `[{}]`\n\n",
                name,
                effects.join(", ")
            ));
        }

        // Types
        for td in &ctx.type_defs {
            match td {
                TypeDef::Sum { name, variants, .. } => {
                    out.push_str(&format!("### type {}\n", name));
                    let vars: Vec<String> = variants
                        .iter()
                        .map(|v| {
                            if v.fields.is_empty() {
                                v.name.clone()
                            } else {
                                format!("{}({})", v.name, v.fields.join(", "))
                            }
                        })
                        .collect();
                    out.push_str(&format!("`{}`\n\n", vars.join("` | `")));
                }
                TypeDef::Product { name, fields, .. } => {
                    out.push_str(&format!("### record {}\n", name));
                    let flds: Vec<String> = fields
                        .iter()
                        .map(|(fname, ftype)| format!("{}: {}", fname, ftype))
                        .collect();
                    out.push_str(&format!("`{}`\n\n", flds.join("`, `")));
                }
            }
        }

        // Functions
        for fd in &ctx.fn_defs {
            if fd.name == "main" {
                continue;
            }

            let params: Vec<String> = fd
                .params
                .iter()
                .map(|(pname, ptype)| format!("{}: {}", pname, ptype))
                .collect();
            out.push_str(&format!(
                "### `{}({}) -> {}`\n",
                fd.name,
                params.join(", "),
                fd.return_type
            ));

            if !fd.effects.is_empty() {
                out.push_str(&format!("effects: `[{}]`  \n", fd.effects.join(", ")));
            }
            out.push_str(&format!(
                "auto_memo: `{}`  \n",
                if ctx.fn_auto_memo.contains(&fd.name) {
                    "true"
                } else {
                    "false"
                }
            ));
            let memo_qual = ctx.fn_memo_qual.get(&fd.name).cloned().unwrap_or_default();
            out.push_str(&format!("memo_qual: `[{}]`  \n", memo_qual.join(", ")));
            out.push_str(&format!(
                "auto_tco: `{}`  \n",
                if ctx.fn_auto_tco.contains(&fd.name) {
                    "true"
                } else {
                    "false"
                }
            ));
            out.push_str(&format!(
                "recursive_callsites: `{}`  \n",
                ctx.fn_recursive_callsites
                    .get(&fd.name)
                    .copied()
                    .unwrap_or(0)
            ));
            out.push_str(&format!(
                "recursive_scc_id: `{}`  \n",
                ctx.fn_recursive_scc_id.get(&fd.name).copied().unwrap_or(0)
            ));
            let specs = ctx.fn_specs.get(&fd.name).cloned().unwrap_or_default();
            if !specs.is_empty() {
                let label = if specs.len() == 1 { "spec" } else { "specs" };
                out.push_str(&format!("{label}: `[{}]`  \n", specs.join(", ")));
            }

            if let Some(desc) = &fd.desc {
                out.push_str(&format!("> {}\n", desc));
            }

            // Verify cases for this function (max 3)
            for vb in ctx.verify_blocks.iter().filter(|vb| vb.fn_name == fd.name) {
                if vb.cases.is_empty() {
                    continue;
                }
                let max = 3usize;
                let shown: Vec<String> = vb
                    .cases
                    .iter()
                    .take(max)
                    .map(|(lhs, rhs)| format!("`{}` → `{}`", expr_to_str(lhs), expr_to_str(rhs)))
                    .collect();
                let extra = if vb.cases.len() > max {
                    format!(" _(+{} more)_", vb.cases.len() - max)
                } else {
                    String::new()
                };
                out.push_str(&format!(
                    "verify_sample_policy_id: `{}`\nverify: {}{}\n",
                    VERIFY_SAMPLE_POLICY_ID,
                    shown.join(", "),
                    extra
                ));
            }

            out.push('\n');
        }
    }

    // Decisions collected from all files
    if !all_decisions.is_empty() {
        out.push_str("---\n\n## Decisions\n\n");
        for dec in all_decisions {
            out.push_str(&format!("### {} ({})\n", dec.name, dec.date));
            out.push_str(&format!("**Chosen:** {}", decision_ref_text(&dec.chosen)));
            if !dec.rejected.is_empty() {
                let rejected = dec
                    .rejected
                    .iter()
                    .map(decision_ref_text)
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(" — **Rejected:** {}", rejected));
            }
            out.push('\n');
            if !dec.reason.is_empty() {
                let reason = if dec.reason.len() > 160 {
                    format!("{}…", dec.reason[..160].trim_end())
                } else {
                    dec.reason.clone()
                };
                out.push_str(&format!("> {}\n", reason));
            }
            if !dec.impacts.is_empty() {
                out.push_str(&format!(
                    "impacts: `{}`\n",
                    impact_texts(&dec.impacts).join("`, `")
                ));
            }
            out.push('\n');
        }
    }

    out
}

pub(super) fn json_str(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    )
}

pub(super) fn format_context_json(contexts: &[FileContext], entry_file: &str) -> String {
    let all_decisions: Vec<&DecisionBlock> =
        contexts.iter().flat_map(|c| c.decisions.iter()).collect();

    let mut out = String::from("{\n");
    out.push_str(&format!(
        "  \"schema_version\": {},\n",
        CONTEXT_SCHEMA_VERSION
    ));
    out.push_str(&format!("  \"entry\": {},\n", json_str(entry_file)));
    out.push_str("  \"analysis_encoding\": {\n");
    out.push_str(&format!(
        "    \"version\": {},\n",
        ANALYSIS_ENCODING_VERSION
    ));
    out.push_str("    \"fields\": {\"f\": \"flags\", \"q\": \"memo_qual\", \"r\": \"recursive_callsites\", \"s\": \"scc_id\"},\n");
    out.push_str("    \"r_scope\": \"scc\",\n");
    out.push_str("    \"flags\": {\"AUTO_MEMO\": 1, \"AUTO_TCO\": 2},\n");
    out.push_str("    \"memo_qual\": {\"PURE\": 1, \"RECURSIVE\": 2, \"SAFE_ARGS\": 4}\n");
    out.push_str("  },\n");
    out.push_str("  \"modules\": [\n");

    let non_empty: Vec<&FileContext> = contexts
        .iter()
        .filter(|c| c.module_name.is_some() || !c.fn_defs.is_empty() || !c.type_defs.is_empty())
        .collect();

    for (mi, ctx) in non_empty.iter().enumerate() {
        let comma_m = if mi + 1 < non_empty.len() { "," } else { "" };
        out.push_str("    {\n");
        out.push_str(&format!(
            "      \"source_file\": {},\n",
            json_str(&ctx.source_file)
        ));
        match &ctx.module_name {
            Some(n) => out.push_str(&format!("      \"module\": {},\n", json_str(n))),
            None => out.push_str("      \"module\": null,\n"),
        }
        match &ctx.intent {
            Some(i) => out.push_str(&format!("      \"intent\": {},\n", json_str(i))),
            None => out.push_str("      \"intent\": null,\n"),
        }
        let api_effects = ctx
            .api_effects
            .iter()
            .map(|e| json_str(e))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("      \"api_effects\": [{}],\n", api_effects));
        let module_effects = ctx
            .module_effects
            .iter()
            .map(|e| json_str(e))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "      \"module_effects\": [{}],\n",
            module_effects
        ));
        match &ctx.main_effects {
            Some(main_effects) => {
                let main_effects_json = main_effects
                    .iter()
                    .map(|e| json_str(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "      \"main_effects\": [{}],\n",
                    main_effects_json
                ));
            }
            None => out.push_str("      \"main_effects\": null,\n"),
        }

        // effect_sets
        out.push_str("      \"effect_sets\": [");
        if ctx.effect_sets.is_empty() {
            out.push_str("],\n");
        } else {
            out.push('\n');
            for (ei, (name, effects)) in ctx.effect_sets.iter().enumerate() {
                let comma_e = if ei + 1 < ctx.effect_sets.len() {
                    ","
                } else {
                    ""
                };
                let effs: Vec<String> = effects.iter().map(|e| json_str(e)).collect();
                out.push_str(&format!(
                    "        {{\"name\": {}, \"effects\": [{}]}}{}\n",
                    json_str(name),
                    effs.join(", "),
                    comma_e
                ));
            }
            out.push_str("      ],\n");
        }

        // types
        out.push_str("      \"types\": [");
        let sum_types: Vec<&TypeDef> = ctx
            .type_defs
            .iter()
            .filter(|td| matches!(td, TypeDef::Sum { .. }))
            .collect();
        if sum_types.is_empty() {
            out.push_str("],\n");
        } else {
            out.push('\n');
            for (ti, td) in sum_types.iter().enumerate() {
                let comma_t = if ti + 1 < sum_types.len() { "," } else { "" };
                if let TypeDef::Sum { name, variants, .. } = td {
                    let vars: Vec<String> = variants
                        .iter()
                        .map(|v| {
                            if v.fields.is_empty() {
                                json_str(&v.name)
                            } else {
                                format!(
                                    "{{\"name\": {}, \"fields\": [{}]}}",
                                    json_str(&v.name),
                                    v.fields
                                        .iter()
                                        .map(|f| json_str(f))
                                        .collect::<Vec<_>>()
                                        .join(", ")
                                )
                            }
                        })
                        .collect();
                    out.push_str(&format!(
                        "        {{\"name\": {}, \"variants\": [{}]}}{}\n",
                        json_str(name),
                        vars.join(", "),
                        comma_t
                    ));
                }
            }
            out.push_str("      ],\n");
        }

        // records
        out.push_str("      \"records\": [");
        let records: Vec<&TypeDef> = ctx
            .type_defs
            .iter()
            .filter(|td| matches!(td, TypeDef::Product { .. }))
            .collect();
        if records.is_empty() {
            out.push_str("],\n");
        } else {
            out.push('\n');
            for (ri, td) in records.iter().enumerate() {
                let comma_r = if ri + 1 < records.len() { "," } else { "" };
                if let TypeDef::Product { name, fields, .. } = td {
                    let flds: Vec<String> = fields
                        .iter()
                        .map(|(fname, ftype)| {
                            format!(
                                "{{\"name\": {}, \"type\": {}}}",
                                json_str(fname),
                                json_str(ftype)
                            )
                        })
                        .collect();
                    out.push_str(&format!(
                        "        {{\"name\": {}, \"fields\": [{}]}}{}\n",
                        json_str(name),
                        flds.join(", "),
                        comma_r
                    ));
                }
            }
            out.push_str("      ],\n");
        }

        // functions
        out.push_str("      \"functions\": [");
        let fns: Vec<&FnDef> = ctx.fn_defs.iter().filter(|fd| fd.name != "main").collect();
        if fns.is_empty() {
            out.push_str("]\n");
        } else {
            out.push('\n');
            for (fi, fd) in fns.iter().enumerate() {
                let comma_f = if fi + 1 < fns.len() { "," } else { "" };
                out.push_str("        {\n");
                out.push_str(&format!("          \"name\": {},\n", json_str(&fd.name)));

                let params: Vec<String> = fd
                    .params
                    .iter()
                    .map(|(pn, pt)| {
                        format!("{{\"name\": {}, \"type\": {}}}", json_str(pn), json_str(pt))
                    })
                    .collect();
                out.push_str(&format!("          \"params\": [{}],\n", params.join(", ")));
                out.push_str(&format!(
                    "          \"return_type\": {},\n",
                    json_str(&fd.return_type)
                ));

                let effs: Vec<String> = fd.effects.iter().map(|e| json_str(e)).collect();
                out.push_str(&format!("          \"effects\": [{}],\n", effs.join(", ")));
                let memo_qual = ctx.fn_memo_qual.get(&fd.name).cloned().unwrap_or_default();
                let mut analysis_flags = 0u8;
                if ctx.fn_auto_memo.contains(&fd.name) {
                    analysis_flags |= ANALYSIS_FLAG_AUTO_MEMO;
                }
                if ctx.fn_auto_tco.contains(&fd.name) {
                    analysis_flags |= ANALYSIS_FLAG_AUTO_TCO;
                }
                let analysis_memo_qual = memo_qual_mask(&memo_qual);
                let analysis_recursive_callsites = ctx
                    .fn_recursive_callsites
                    .get(&fd.name)
                    .copied()
                    .unwrap_or(0);
                let analysis_recursive_scc_id =
                    ctx.fn_recursive_scc_id.get(&fd.name).copied().unwrap_or(0);
                out.push_str(&format!(
                    "          \"analysis\": {{\"f\": {}, \"q\": {}, \"r\": {}, \"s\": {}}},\n",
                    analysis_flags,
                    analysis_memo_qual,
                    analysis_recursive_callsites,
                    analysis_recursive_scc_id
                ));

                match &fd.desc {
                    Some(d) => out.push_str(&format!("          \"desc\": {},\n", json_str(d))),
                    None => out.push_str("          \"desc\": null,\n"),
                }
                let specs = ctx.fn_specs.get(&fd.name).cloned().unwrap_or_default();
                let specs_json = specs
                    .iter()
                    .map(|spec| json_str(spec))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("          \"specs\": [{}],\n", specs_json));

                // verify cases (compact JSON: first sample + full count)
                let verify_total = ctx
                    .verify_blocks
                    .iter()
                    .filter(|vb| vb.fn_name == fd.name)
                    .map(|vb| vb.cases.len())
                    .sum::<usize>();
                out.push_str(&format!("          \"verify_count\": {},\n", verify_total));
                if verify_total > 0 {
                    out.push_str(&format!(
                        "          \"verify_sample_policy_id\": {},\n",
                        json_str(VERIFY_SAMPLE_POLICY_ID)
                    ));
                }

                out.push_str("          \"verify\": [");
                let verify_cases: Vec<String> = ctx
                    .verify_blocks
                    .iter()
                    .filter(|vb| vb.fn_name == fd.name)
                    .flat_map(|vb| vb.cases.iter())
                    .take(JSON_VERIFY_SAMPLE_LIMIT)
                    .map(|(lhs, rhs)| {
                        format!(
                            "{{\"input\": {}, \"expected\": {}}}",
                            json_str(&expr_to_str(lhs)),
                            json_str(&expr_to_str(rhs))
                        )
                    })
                    .collect();
                if verify_cases.is_empty() {
                    out.push_str("]\n");
                } else {
                    out.push_str(&format!("{}]\n", verify_cases.join(", ")));
                }

                out.push_str(&format!("        }}{}\n", comma_f));
            }
            out.push_str("      ]\n");
        }

        out.push_str(&format!("    }}{}\n", comma_m));
    }

    out.push_str("  ],\n");

    // decisions
    out.push_str("  \"decisions\": [");
    if all_decisions.is_empty() {
        out.push_str("]\n");
    } else {
        out.push('\n');
        for (di, dec) in all_decisions.iter().enumerate() {
            let comma_d = if di + 1 < all_decisions.len() {
                ","
            } else {
                ""
            };
            out.push_str("    {\n");
            out.push_str(&format!("      \"name\": {},\n", json_str(&dec.name)));
            out.push_str(&format!("      \"date\": {},\n", json_str(&dec.date)));
            out.push_str(&format!(
                "      \"chosen\": {},\n",
                json_str(decision_ref_json_text(&dec.chosen))
            ));
            let rej: Vec<String> = dec
                .rejected
                .iter()
                .map(|r| json_str(decision_ref_json_text(r)))
                .collect();
            out.push_str(&format!("      \"rejected\": [{}],\n", rej.join(", ")));
            out.push_str(&format!("      \"reason\": {},\n", json_str(&dec.reason)));
            let imp: Vec<String> = impact_json_texts(&dec.impacts)
                .iter()
                .map(|i| json_str(i))
                .collect();
            out.push_str(&format!("      \"impacts\": [{}],\n", imp.join(", ")));
            match &dec.author {
                Some(a) => out.push_str(&format!("      \"author\": {}\n", json_str(a))),
                None => out.push_str("      \"author\": null\n"),
            }
            out.push_str(&format!("    }}{}\n", comma_d));
        }
        out.push_str("  ]\n");
    }

    out.push('}');
    out
}

pub(super) fn collect_all_decisions(contexts: &[FileContext]) -> Vec<&DecisionBlock> {
    contexts
        .iter()
        .flat_map(|ctx| ctx.decisions.iter())
        .collect()
}

pub(super) fn format_decisions_md(decisions: &[&DecisionBlock], entry_file: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Aver Decisions - {}\n\n", entry_file));
    out.push_str("_Generated by `aver context --decisions-only`_\n\n");
    if decisions.is_empty() {
        out.push_str("No decision blocks found.\n");
        return out;
    }

    for dec in decisions {
        out.push_str(&format!("## {} ({})\n\n", dec.name, dec.date));
        out.push_str(&format!("**Chosen:** {}\n", decision_ref_text(&dec.chosen)));
        if !dec.rejected.is_empty() {
            let rejected = dec
                .rejected
                .iter()
                .map(decision_ref_text)
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("**Rejected:** {}\n", rejected));
        }
        if !dec.impacts.is_empty() {
            out.push_str(&format!(
                "**Impacts:** {}\n",
                impact_texts(&dec.impacts).join(", ")
            ));
        }
        if !dec.reason.is_empty() {
            out.push_str(&format!("\n> {}\n", dec.reason));
        }
        if let Some(author) = &dec.author {
            out.push_str(&format!("\nAuthor: `{}`\n", author));
        }
        out.push('\n');
    }

    out
}

pub(super) fn format_decisions_json(decisions: &[&DecisionBlock], entry_file: &str) -> String {
    let mut out = String::from("{\n");
    out.push_str(&format!("  \"entry\": {},\n", json_str(entry_file)));
    out.push_str("  \"decisions\": [");
    if decisions.is_empty() {
        out.push_str("]\n");
    } else {
        out.push('\n');
        for (di, dec) in decisions.iter().enumerate() {
            let comma_d = if di + 1 < decisions.len() { "," } else { "" };
            out.push_str("    {\n");
            out.push_str(&format!("      \"name\": {},\n", json_str(&dec.name)));
            out.push_str(&format!("      \"date\": {},\n", json_str(&dec.date)));
            out.push_str(&format!(
                "      \"chosen\": {},\n",
                json_str(decision_ref_json_text(&dec.chosen))
            ));
            let rej: Vec<String> = dec
                .rejected
                .iter()
                .map(|r| json_str(decision_ref_json_text(r)))
                .collect();
            out.push_str(&format!("      \"rejected\": [{}],\n", rej.join(", ")));
            out.push_str(&format!("      \"reason\": {},\n", json_str(&dec.reason)));
            let imp: Vec<String> = impact_json_texts(&dec.impacts)
                .iter()
                .map(|i| json_str(i))
                .collect();
            out.push_str(&format!("      \"impacts\": [{}],\n", imp.join(", ")));
            match &dec.author {
                Some(a) => out.push_str(&format!("      \"author\": {}\n", json_str(a))),
                None => out.push_str("      \"author\": null\n"),
            }
            out.push_str(&format!("    }}{}\n", comma_d));
        }
        out.push_str("  ]\n");
    }
    out.push('}');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::{HashMap, HashSet};

    fn file_context_with_spec() -> FileContext {
        FileContext {
            source_file: "examples/spec.av".to_string(),
            module_name: Some("Spec".to_string()),
            intent: Some("spec demo".to_string()),
            exposes: vec!["fib".to_string()],
            api_effects: vec![],
            module_effects: vec![],
            main_effects: None,
            fn_defs: vec![FnDef {
                name: "fib".to_string(),
                line: 1,
                params: vec![("n".to_string(), "Int".to_string())],
                return_type: "Int".to_string(),
                effects: vec![],
                desc: Some("demo".to_string()),
                body: std::rc::Rc::new(aver::ast::FnBody::Block(vec![])),
                resolution: None,
            }],
            fn_auto_memo: HashSet::new(),
            fn_memo_qual: HashMap::new(),
            fn_auto_tco: HashSet::new(),
            fn_recursive_callsites: HashMap::new(),
            fn_recursive_scc_id: HashMap::new(),
            fn_specs: HashMap::from([("fib".to_string(), vec!["fibSpec".to_string()])]),
            type_defs: vec![],
            effect_sets: vec![],
            verify_blocks: vec![],
            decisions: vec![],
        }
    }

    #[test]
    fn markdown_context_renders_spec_refs() {
        let out = format_context_md(&[file_context_with_spec()], "examples/spec.av");
        assert!(out.contains("spec: `[fibSpec]`"));
    }

    #[test]
    fn json_context_renders_specs_array() {
        let out = format_context_json(&[file_context_with_spec()], "examples/spec.av");
        assert!(out.contains("\"schema_version\": 4"));
        assert!(out.contains("\"specs\": [\"fibSpec\"]"));
    }
}
