use aver::ast::{DecisionBlock, DecisionImpact, FnDef, TypeDef};

use crate::context_data::FileContext;

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct ContextSelection {
    pub depth_mode: String,
    pub budget_bytes: Option<usize>,
    pub included_depth: Option<usize>,
    pub next_depth: Option<usize>,
    pub next_used_bytes: Option<usize>,
    pub truncated: bool,
    pub used_bytes: usize,
    pub focus_symbol: Option<String>,
    /// How many elements (fns, types, decisions) were selected vs available.
    pub elements_selected: Option<usize>,
    pub elements_total: Option<usize>,
}

fn impact_texts(impacts: &[DecisionImpact]) -> Vec<String> {
    impacts
        .iter()
        .map(DecisionImpact::as_context_string)
        .collect()
}

fn impact_json_texts(impacts: &[DecisionImpact]) -> Vec<String> {
    impacts
        .iter()
        .map(|impact| impact.text().to_string())
        .collect()
}

fn decision_ref_text(reference: &DecisionImpact) -> String {
    reference.as_context_string()
}

fn decision_ref_json_text(reference: &DecisionImpact) -> &str {
    reference.text()
}

const CONTEXT_SCHEMA_VERSION: u32 = 6;

fn fn_sig(fd: &FnDef) -> String {
    let params: Vec<String> = fd
        .params
        .iter()
        .map(|(pname, ptype)| format!("{}: {}", pname, ptype))
        .collect();
    format!("{}({}) -> {}", fd.name, params.join(", "), fd.return_type)
}

fn effects_equal(a: &[String], b: &[String]) -> bool {
    a.len() == b.len() && a.iter().zip(b.iter()).all(|(x, y)| x == y)
}

fn byte_label(bytes: usize) -> String {
    if bytes >= 1024 * 1024 && bytes.is_multiple_of(1024 * 1024) {
        format!("{}mb", bytes / (1024 * 1024))
    } else if bytes >= 1024 && bytes.is_multiple_of(1024) {
        format!("{}kb", bytes / 1024)
    } else {
        format!("{}b", bytes)
    }
}

pub(super) fn format_context_md(
    contexts: &[FileContext],
    entry_file: &str,
    selection: Option<&ContextSelection>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Aver Context — {}\n\n", entry_file));
    out.push_str("_Generated by `aver context`_\n\n");
    if let Some(selection) = selection {
        let mut parts = vec![format!("mode: `{}`", selection.depth_mode)];
        if let Some(budget) = selection.budget_bytes {
            parts.push(format!("budget: `{}`", byte_label(budget)));
        }
        if let Some(depth) = selection.included_depth {
            parts.push(format!("included_depth: `{}`", depth));
        }
        if let Some(next_depth) = selection.next_depth {
            parts.push(format!("next_depth: `{}`", next_depth));
        }
        if let Some(next_used) = selection.next_used_bytes {
            parts.push(format!("next_used: `{}`", byte_label(next_used)));
        }
        if let Some(focus_symbol) = &selection.focus_symbol {
            parts.push(format!("focus: `{}`", focus_symbol));
        }
        if let (Some(selected), Some(total)) =
            (selection.elements_selected, selection.elements_total)
        {
            parts.push(format!("selected: `{}/{}`", selected, total));
        }
        parts.push(format!("truncated: `{}`", selection.truncated));
        parts.push(format!("used: `{}`", byte_label(selection.used_bytes)));
        out.push_str(&format!("selection: {}\n\n", parts.join(", ")));
    }

    let all_decisions: Vec<&DecisionBlock> =
        contexts.iter().flat_map(|c| c.decisions.iter()).collect();

    for ctx in contexts {
        let has_content =
            !ctx.fn_defs.is_empty() || !ctx.type_defs.is_empty() || !ctx.effect_sets.is_empty();

        if !has_content && ctx.module_name.is_none() {
            continue;
        }

        out.push_str("---\n\n");

        if let Some(name) = &ctx.module_name {
            out.push_str(&format!("## Module: {}\n\n", name));
        } else {
            out.push_str(&format!("## {}\n\n", ctx.source_file));
        }

        if let Some(intent) = &ctx.intent {
            out.push_str(&format!("> {}\n\n", intent));
        }

        // Effects: merge api/module when identical
        if effects_equal(&ctx.api_effects, &ctx.module_effects) {
            if !ctx.module_effects.is_empty() {
                out.push_str(&format!("effects: `[{}]`\n", ctx.module_effects.join(", ")));
            }
        } else {
            out.push_str(&format!(
                "api_effects: `[{}]`  \nmodule_effects: `[{}]`\n",
                ctx.api_effects.join(", "),
                ctx.module_effects.join(", ")
            ));
        }
        if let Some(main_effects) = &ctx.main_effects {
            out.push_str(&format!("main_effects: `[{}]`\n", main_effects.join(", ")));
        }
        out.push('\n');

        // Effect set aliases
        for (name, effects) in &ctx.effect_sets {
            out.push_str(&format!(
                "**effects** `{}` = `[{}]`\n\n",
                name,
                effects.join(", ")
            ));
        }

        // Types
        for td in &ctx.type_defs {
            match td {
                TypeDef::Sum { name, variants, .. } => {
                    out.push_str(&format!("### type {}\n", name));
                    let vars: Vec<String> = variants
                        .iter()
                        .map(|v| {
                            if v.fields.is_empty() {
                                v.name.clone()
                            } else {
                                format!("{}({})", v.name, v.fields.join(", "))
                            }
                        })
                        .collect();
                    out.push_str(&format!("`{}`\n\n", vars.join("` | `")));
                }
                TypeDef::Product { name, fields, .. } => {
                    out.push_str(&format!("### record {}\n", name));
                    let flds: Vec<String> = fields
                        .iter()
                        .map(|(fname, ftype)| format!("{}: {}", fname, ftype))
                        .collect();
                    out.push_str(&format!("`{}`\n\n", flds.join("`, `")));
                }
            }
        }

        // Functions
        for fd in &ctx.fn_defs {
            if fd.name == "main" {
                continue;
            }

            out.push_str(&format!("### `{}`\n", fn_sig(fd)));

            if !fd.effects.is_empty() {
                out.push_str(&format!("effects: `[{}]`  \n", fd.effects.join(", ")));
            }

            // Only show analysis flags when non-default
            if ctx.fn_auto_memo.contains(&fd.name) {
                out.push_str("memo: `true`  \n");
            }
            if ctx.fn_auto_tco.contains(&fd.name) {
                out.push_str("tco: `true`  \n");
            }

            let specs = ctx.fn_specs.get(&fd.name).cloned().unwrap_or_default();
            if !specs.is_empty() {
                let label = if specs.len() == 1 { "spec" } else { "specs" };
                out.push_str(&format!("{label}: `[{}]`  \n", specs.join(", ")));
            }

            if let Some(desc) = &fd.desc {
                out.push_str(&format!("> {}\n", desc));
            }

            let verify_samples: Vec<String> = ctx
                .verify_samples
                .get(&fd.name)
                .cloned()
                .unwrap_or_default()
                .into_iter()
                .map(|sample| format!("`{sample}`"))
                .collect();
            if !verify_samples.is_empty() {
                out.push_str(&format!("verify: {}\n", verify_samples.join(", ")));
            }

            out.push('\n');
        }
    }

    // Decisions collected from all files
    if !all_decisions.is_empty() {
        out.push_str("---\n\n## Decisions\n\n");
        for dec in all_decisions {
            out.push_str(&format!("### {} ({})\n", dec.name, dec.date));
            out.push_str(&format!("**Chosen:** {}", decision_ref_text(&dec.chosen)));
            if !dec.rejected.is_empty() {
                let rejected = dec
                    .rejected
                    .iter()
                    .map(decision_ref_text)
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(" — **Rejected:** {}", rejected));
            }
            out.push('\n');
            if !dec.reason.is_empty() {
                let reason = if dec.reason.len() > 160 {
                    format!("{}…", dec.reason[..160].trim_end())
                } else {
                    dec.reason.clone()
                };
                out.push_str(&format!("> {}\n", reason));
            }
            if !dec.impacts.is_empty() {
                out.push_str(&format!(
                    "impacts: `{}`\n",
                    impact_texts(&dec.impacts).join("`, `")
                ));
            }
            out.push('\n');
        }
    }

    out
}

pub(super) fn json_str(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    )
}

pub(super) fn format_context_json(
    contexts: &[FileContext],
    entry_file: &str,
    selection: Option<&ContextSelection>,
) -> String {
    let all_decisions: Vec<&DecisionBlock> =
        contexts.iter().flat_map(|c| c.decisions.iter()).collect();

    let mut out = String::from("{\n");
    out.push_str(&format!(
        "  \"schema_version\": {},\n",
        CONTEXT_SCHEMA_VERSION
    ));
    out.push_str(&format!("  \"entry\": {},\n", json_str(entry_file)));
    if let Some(selection) = selection {
        out.push_str("  \"selection\": {\n");
        out.push_str(&format!(
            "    \"depth_mode\": {},\n",
            json_str(&selection.depth_mode)
        ));
        if let Some(budget) = selection.budget_bytes {
            out.push_str(&format!("    \"budget_bytes\": {},\n", budget));
        }
        if let Some(depth) = selection.included_depth {
            out.push_str(&format!("    \"included_depth\": {},\n", depth));
        }
        if let Some(next_depth) = selection.next_depth {
            out.push_str(&format!("    \"next_depth\": {},\n", next_depth));
        }
        if let Some(next_used) = selection.next_used_bytes {
            out.push_str(&format!("    \"next_used_bytes\": {},\n", next_used));
        }
        if let Some(focus_symbol) = &selection.focus_symbol {
            out.push_str(&format!(
                "    \"focus_symbol\": {},\n",
                json_str(focus_symbol)
            ));
        }
        if let (Some(selected), Some(total)) =
            (selection.elements_selected, selection.elements_total)
        {
            out.push_str(&format!("    \"elements_selected\": {},\n", selected));
            out.push_str(&format!("    \"elements_total\": {},\n", total));
        }
        out.push_str(&format!(
            "    \"truncated\": {},\n",
            if selection.truncated { "true" } else { "false" }
        ));
        out.push_str(&format!("    \"used_bytes\": {}\n", selection.used_bytes));
        out.push_str("  },\n");
    }
    out.push_str("  \"modules\": [\n");

    let non_empty: Vec<&FileContext> = contexts
        .iter()
        .filter(|c| c.module_name.is_some() || !c.fn_defs.is_empty() || !c.type_defs.is_empty())
        .collect();

    for (mi, ctx) in non_empty.iter().enumerate() {
        let comma_m = if mi + 1 < non_empty.len() { "," } else { "" };
        out.push_str("    {\n");
        out.push_str(&format!(
            "      \"source_file\": {},\n",
            json_str(&ctx.source_file)
        ));
        if let Some(n) = &ctx.module_name {
            out.push_str(&format!("      \"module\": {},\n", json_str(n)));
        }
        if let Some(i) = &ctx.intent {
            out.push_str(&format!("      \"intent\": {},\n", json_str(i)));
        }
        if !ctx.depends.is_empty() {
            let depends = ctx
                .depends
                .iter()
                .map(|dep| json_str(dep))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("      \"depends\": [{}],\n", depends));
        }

        // Effects: merge when identical, omit when empty
        if effects_equal(&ctx.api_effects, &ctx.module_effects) {
            if !ctx.module_effects.is_empty() {
                let effs = ctx
                    .module_effects
                    .iter()
                    .map(|e| json_str(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("      \"effects\": [{}],\n", effs));
            }
        } else {
            let api = ctx
                .api_effects
                .iter()
                .map(|e| json_str(e))
                .collect::<Vec<_>>()
                .join(", ");
            let module = ctx
                .module_effects
                .iter()
                .map(|e| json_str(e))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("      \"api_effects\": [{}],\n", api));
            out.push_str(&format!("      \"module_effects\": [{}],\n", module));
        }

        if let Some(main_effects) = &ctx.main_effects {
            let main_effs = main_effects
                .iter()
                .map(|e| json_str(e))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("      \"main_effects\": [{}],\n", main_effs));
        }

        // effect_sets — omit key when empty
        if !ctx.effect_sets.is_empty() {
            out.push_str("      \"effect_sets\": [\n");
            for (ei, (name, effects)) in ctx.effect_sets.iter().enumerate() {
                let comma_e = if ei + 1 < ctx.effect_sets.len() {
                    ","
                } else {
                    ""
                };
                let effs: Vec<String> = effects.iter().map(|e| json_str(e)).collect();
                out.push_str(&format!(
                    "        {{\"name\": {}, \"effects\": [{}]}}{}\n",
                    json_str(name),
                    effs.join(", "),
                    comma_e
                ));
            }
            out.push_str("      ],\n");
        }

        // types — omit key when empty
        let sum_types: Vec<&TypeDef> = ctx
            .type_defs
            .iter()
            .filter(|td| matches!(td, TypeDef::Sum { .. }))
            .collect();
        if !sum_types.is_empty() {
            out.push_str("      \"types\": [\n");
            for (ti, td) in sum_types.iter().enumerate() {
                let comma_t = if ti + 1 < sum_types.len() { "," } else { "" };
                if let TypeDef::Sum { name, variants, .. } = td {
                    let vars: Vec<String> = variants
                        .iter()
                        .map(|v| {
                            if v.fields.is_empty() {
                                json_str(&v.name)
                            } else {
                                format!(
                                    "{{\"name\": {}, \"fields\": [{}]}}",
                                    json_str(&v.name),
                                    v.fields
                                        .iter()
                                        .map(|f| json_str(f))
                                        .collect::<Vec<_>>()
                                        .join(", ")
                                )
                            }
                        })
                        .collect();
                    out.push_str(&format!(
                        "        {{\"name\": {}, \"variants\": [{}]}}{}\n",
                        json_str(name),
                        vars.join(", "),
                        comma_t
                    ));
                }
            }
            out.push_str("      ],\n");
        }

        // records — omit key when empty
        let records: Vec<&TypeDef> = ctx
            .type_defs
            .iter()
            .filter(|td| matches!(td, TypeDef::Product { .. }))
            .collect();
        if !records.is_empty() {
            out.push_str("      \"records\": [\n");
            for (ri, td) in records.iter().enumerate() {
                let comma_r = if ri + 1 < records.len() { "," } else { "" };
                if let TypeDef::Product { name, fields, .. } = td {
                    let flds: Vec<String> = fields
                        .iter()
                        .map(|(fname, ftype)| {
                            format!(
                                "{{\"name\": {}, \"type\": {}}}",
                                json_str(fname),
                                json_str(ftype)
                            )
                        })
                        .collect();
                    out.push_str(&format!(
                        "        {{\"name\": {}, \"fields\": [{}]}}{}\n",
                        json_str(name),
                        flds.join(", "),
                        comma_r
                    ));
                }
            }
            out.push_str("      ],\n");
        }

        let fns: Vec<&FnDef> = ctx.fn_defs.iter().filter(|fd| fd.name != "main").collect();
        if !fns.is_empty() {
            out.push_str("      \"functions\": [\n");
            for (fi, fd) in fns.iter().enumerate() {
                let comma_f = if fi + 1 < fns.len() { "," } else { "" };
                out.push_str("        {\n");
                out.push_str(&format!("          \"sig\": {},\n", json_str(&fn_sig(fd))));

                if !fd.effects.is_empty() {
                    let effs: Vec<String> = fd.effects.iter().map(|e| json_str(e)).collect();
                    out.push_str(&format!("          \"effects\": [{}],\n", effs.join(", ")));
                }

                // Analysis — only when non-default
                let has_memo = ctx.fn_auto_memo.contains(&fd.name);
                let has_tco = ctx.fn_auto_tco.contains(&fd.name);
                if has_memo || has_tco {
                    let mut analysis_fields = Vec::new();
                    if has_memo {
                        analysis_fields.push("\"memo\": true".to_string());
                    }
                    if has_tco {
                        analysis_fields.push("\"tco\": true".to_string());
                    }
                    out.push_str(&format!(
                        "          \"analysis\": {{{}}},\n",
                        analysis_fields.join(", ")
                    ));
                }

                if let Some(d) = &fd.desc {
                    out.push_str(&format!("          \"desc\": {},\n", json_str(d)));
                }

                let specs = ctx.fn_specs.get(&fd.name).cloned().unwrap_or_default();
                if !specs.is_empty() {
                    let specs_json = specs
                        .iter()
                        .map(|spec| json_str(spec))
                        .collect::<Vec<_>>()
                        .join(", ");
                    out.push_str(&format!("          \"specs\": [{}],\n", specs_json));
                }

                let verify_total = ctx.verify_counts.get(&fd.name).copied().unwrap_or(0);
                if verify_total > 0 {
                    out.push_str(&format!("          \"verify_count\": {},\n", verify_total));
                }

                let verify_cases: Vec<String> = ctx
                    .verify_samples
                    .get(&fd.name)
                    .cloned()
                    .unwrap_or_default()
                    .into_iter()
                    .map(|sample| json_str(&sample))
                    .collect();

                if !verify_cases.is_empty() {
                    out.push_str(&format!(
                        "          \"verify\": [{}]\n",
                        verify_cases.join(", ")
                    ));
                } else {
                    // Trim trailing comma from last field
                    if out.ends_with(",\n") {
                        out.truncate(out.len() - 2);
                        out.push('\n');
                    }
                }

                out.push_str(&format!("        }}{}\n", comma_f));
            }
            out.push_str("      ]\n");
        } else if out.ends_with(",\n") {
            out.truncate(out.len() - 2);
            out.push('\n');
        }

        out.push_str(&format!("    }}{}\n", comma_m));
    }

    if all_decisions.is_empty() {
        out.push_str("  ]\n");
        out.push('}');
        return out;
    }

    out.push_str("  ],\n");

    // decisions
    out.push_str("  \"decisions\": [");
    out.push('\n');
    for (di, dec) in all_decisions.iter().enumerate() {
        let comma_d = if di + 1 < all_decisions.len() {
            ","
        } else {
            ""
        };
        out.push_str("    {\n");
        out.push_str(&format!("      \"name\": {},\n", json_str(&dec.name)));
        out.push_str(&format!("      \"date\": {},\n", json_str(&dec.date)));
        out.push_str(&format!(
            "      \"chosen\": {},\n",
            json_str(decision_ref_json_text(&dec.chosen))
        ));
        let rej: Vec<String> = dec
            .rejected
            .iter()
            .map(|r| json_str(decision_ref_json_text(r)))
            .collect();
        out.push_str(&format!("      \"rejected\": [{}],\n", rej.join(", ")));
        out.push_str(&format!("      \"reason\": {},\n", json_str(&dec.reason)));
        let imp: Vec<String> = impact_json_texts(&dec.impacts)
            .iter()
            .map(|i| json_str(i))
            .collect();
        out.push_str(&format!("      \"impacts\": [{}],\n", imp.join(", ")));
        if let Some(a) = &dec.author {
            out.push_str(&format!("      \"author\": {}\n", json_str(a)));
        }
        // Trim trailing comma if author was omitted
        if out.ends_with(",\n") {
            out.truncate(out.len() - 2);
            out.push('\n');
        }
        out.push_str(&format!("    }}{}\n", comma_d));
    }
    out.push_str("  ]\n");

    out.push('}');
    out
}

pub(super) fn collect_all_decisions(contexts: &[FileContext]) -> Vec<&DecisionBlock> {
    contexts
        .iter()
        .flat_map(|ctx| ctx.decisions.iter())
        .collect()
}

pub(super) fn format_decisions_md(
    decisions: &[&DecisionBlock],
    entry_file: &str,
    selection: Option<&ContextSelection>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Aver Decisions - {}\n\n", entry_file));
    out.push_str("_Generated by `aver context --decisions-only`_\n\n");
    if let Some(selection) = selection {
        let mut parts = vec![format!("mode: `{}`", selection.depth_mode)];
        if let Some(budget) = selection.budget_bytes {
            parts.push(format!("budget: `{}`", byte_label(budget)));
        }
        if let Some(depth) = selection.included_depth {
            parts.push(format!("included_depth: `{}`", depth));
        }
        if let Some(next_depth) = selection.next_depth {
            parts.push(format!("next_depth: `{}`", next_depth));
        }
        if let Some(next_used) = selection.next_used_bytes {
            parts.push(format!("next_used: `{}`", byte_label(next_used)));
        }
        if let Some(focus_symbol) = &selection.focus_symbol {
            parts.push(format!("focus: `{}`", focus_symbol));
        }
        if let (Some(selected), Some(total)) =
            (selection.elements_selected, selection.elements_total)
        {
            parts.push(format!("selected: `{}/{}`", selected, total));
        }
        parts.push(format!("truncated: `{}`", selection.truncated));
        parts.push(format!("used: `{}`", byte_label(selection.used_bytes)));
        out.push_str(&format!("selection: {}\n\n", parts.join(", ")));
    }
    if decisions.is_empty() {
        out.push_str("No decision blocks found.\n");
        return out;
    }

    for dec in decisions {
        out.push_str(&format!("## {} ({})\n\n", dec.name, dec.date));
        out.push_str(&format!("**Chosen:** {}\n", decision_ref_text(&dec.chosen)));
        if !dec.rejected.is_empty() {
            let rejected = dec
                .rejected
                .iter()
                .map(decision_ref_text)
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("**Rejected:** {}\n", rejected));
        }
        if !dec.impacts.is_empty() {
            out.push_str(&format!(
                "**Impacts:** {}\n",
                impact_texts(&dec.impacts).join(", ")
            ));
        }
        if !dec.reason.is_empty() {
            out.push_str(&format!("\n> {}\n", dec.reason));
        }
        if let Some(author) = &dec.author {
            out.push_str(&format!("\nAuthor: `{}`\n", author));
        }
        out.push('\n');
    }

    out
}

pub(super) fn format_decisions_json(
    decisions: &[&DecisionBlock],
    entry_file: &str,
    selection: Option<&ContextSelection>,
) -> String {
    let mut out = String::from("{\n");
    out.push_str(&format!("  \"entry\": {},\n", json_str(entry_file)));
    if let Some(selection) = selection {
        out.push_str("  \"selection\": {\n");
        out.push_str(&format!(
            "    \"depth_mode\": {},\n",
            json_str(&selection.depth_mode)
        ));
        if let Some(budget) = selection.budget_bytes {
            out.push_str(&format!("    \"budget_bytes\": {},\n", budget));
        }
        if let Some(depth) = selection.included_depth {
            out.push_str(&format!("    \"included_depth\": {},\n", depth));
        }
        if let Some(next_depth) = selection.next_depth {
            out.push_str(&format!("    \"next_depth\": {},\n", next_depth));
        }
        if let Some(next_used) = selection.next_used_bytes {
            out.push_str(&format!("    \"next_used_bytes\": {},\n", next_used));
        }
        if let Some(focus_symbol) = &selection.focus_symbol {
            out.push_str(&format!(
                "    \"focus_symbol\": {},\n",
                json_str(focus_symbol)
            ));
        }
        if let (Some(selected), Some(total)) =
            (selection.elements_selected, selection.elements_total)
        {
            out.push_str(&format!("    \"elements_selected\": {},\n", selected));
            out.push_str(&format!("    \"elements_total\": {},\n", total));
        }
        out.push_str(&format!(
            "    \"truncated\": {},\n",
            if selection.truncated { "true" } else { "false" }
        ));
        out.push_str(&format!("    \"used_bytes\": {}\n", selection.used_bytes));
        out.push_str("  },\n");
    }
    out.push_str("  \"decisions\": [");
    if decisions.is_empty() {
        out.push_str("]\n");
    } else {
        out.push('\n');
        for (di, dec) in decisions.iter().enumerate() {
            let comma_d = if di + 1 < decisions.len() { "," } else { "" };
            out.push_str("    {\n");
            out.push_str(&format!("      \"name\": {},\n", json_str(&dec.name)));
            out.push_str(&format!("      \"date\": {},\n", json_str(&dec.date)));
            out.push_str(&format!(
                "      \"chosen\": {},\n",
                json_str(decision_ref_json_text(&dec.chosen))
            ));
            let rej: Vec<String> = dec
                .rejected
                .iter()
                .map(|r| json_str(decision_ref_json_text(r)))
                .collect();
            out.push_str(&format!("      \"rejected\": [{}],\n", rej.join(", ")));
            out.push_str(&format!("      \"reason\": {},\n", json_str(&dec.reason)));
            let imp: Vec<String> = impact_json_texts(&dec.impacts)
                .iter()
                .map(|i| json_str(i))
                .collect();
            out.push_str(&format!("      \"impacts\": [{}],\n", imp.join(", ")));
            if let Some(a) = &dec.author {
                out.push_str(&format!("      \"author\": {}\n", json_str(a)));
            }
            if out.ends_with(",\n") {
                out.truncate(out.len() - 2);
                out.push('\n');
            }
            out.push_str(&format!("    }}{}\n", comma_d));
        }
        out.push_str("  ]\n");
    }
    out.push('}');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::{HashMap, HashSet};

    fn file_context_with_spec() -> FileContext {
        FileContext {
            source_file: "examples/spec.av".to_string(),
            module_name: Some("Spec".to_string()),
            intent: Some("spec demo".to_string()),
            depends: vec!["Math.Core".to_string()],
            exposes: vec!["fib".to_string()],
            api_effects: vec![],
            module_effects: vec![],
            main_effects: None,
            fn_defs: vec![FnDef {
                name: "fib".to_string(),
                line: 1,
                params: vec![("n".to_string(), "Int".to_string())],
                return_type: "Int".to_string(),
                effects: vec![],
                desc: Some("demo".to_string()),
                body: std::rc::Rc::new(aver::ast::FnBody::Block(vec![])),
                resolution: None,
            }],
            all_fn_defs: vec![FnDef {
                name: "fib".to_string(),
                line: 1,
                params: vec![("n".to_string(), "Int".to_string())],
                return_type: "Int".to_string(),
                effects: vec![],
                desc: Some("demo".to_string()),
                body: std::rc::Rc::new(aver::ast::FnBody::Block(vec![])),
                resolution: None,
            }],
            fn_auto_memo: HashSet::new(),
            fn_memo_qual: HashMap::new(),
            fn_auto_tco: HashSet::new(),
            fn_recursive_callsites: HashMap::new(),
            fn_recursive_scc_id: HashMap::new(),
            fn_specs: HashMap::from([("fib".to_string(), vec!["fibSpec".to_string()])]),
            fn_direct_calls: HashMap::new(),
            type_defs: vec![],
            effect_sets: vec![],
            verify_blocks: vec![aver::ast::VerifyBlock {
                fn_name: "fib".to_string(),
                line: 2,
                cases: vec![(
                    aver::ast::Expr::FnCall(
                        Box::new(aver::ast::Expr::Ident("fib".to_string())),
                        vec![aver::ast::Expr::Literal(aver::ast::Literal::Int(5))],
                    ),
                    aver::ast::Expr::Literal(aver::ast::Literal::Int(8)),
                )],
                kind: aver::ast::VerifyKind::Cases,
            }],
            verify_counts: HashMap::from([("fib".to_string(), 1)]),
            verify_samples: HashMap::from([("fib".to_string(), vec!["fib(5) → 8".to_string()])]),
            decisions: vec![],
        }
    }

    #[test]
    fn markdown_context_renders_spec_refs() {
        let out = format_context_md(&[file_context_with_spec()], "examples/spec.av", None);
        assert!(out.contains("spec: `[fibSpec]`"));
    }

    #[test]
    fn json_context_renders_specs_array() {
        let out = format_context_json(&[file_context_with_spec()], "examples/spec.av", None);
        assert!(out.contains("\"schema_version\": 6"));
        assert!(out.contains("\"depends\": [\"Math.Core\"]"));
        assert!(out.contains("\"sig\": \"fib(n: Int) -> Int\""));
        assert!(out.contains("\"specs\": [\"fibSpec\"]"));
        assert!(out.contains("\"verify_count\": 1"));
        assert!(out.contains("\"verify\": [\"fib(5) → 8\"]"));
    }

    #[test]
    fn json_context_renders_compact_analysis() {
        let mut ctx = file_context_with_spec();
        ctx.fn_auto_memo.insert("fib".to_string());
        ctx.fn_auto_tco.insert("fib".to_string());

        let out = format_context_json(&[ctx], "examples/spec.av", None);
        assert!(out.contains("\"analysis\": {\"memo\": true, \"tco\": true}"));
        assert!(!out.contains("\"memo\": true,\n"));
        assert!(!out.contains("\"tco\": true,\n"));
    }

    #[test]
    fn json_context_omits_empty_fields() {
        let ctx = FileContext {
            source_file: "examples/main.av".to_string(),
            module_name: None,
            intent: None,
            depends: vec![],
            exposes: vec![],
            api_effects: vec![],
            module_effects: vec![],
            main_effects: None,
            fn_defs: vec![FnDef {
                name: "main".to_string(),
                line: 1,
                params: vec![],
                return_type: "Unit".to_string(),
                effects: vec![],
                desc: None,
                body: std::rc::Rc::new(aver::ast::FnBody::Block(vec![])),
                resolution: None,
            }],
            all_fn_defs: vec![FnDef {
                name: "main".to_string(),
                line: 1,
                params: vec![],
                return_type: "Unit".to_string(),
                effects: vec![],
                desc: None,
                body: std::rc::Rc::new(aver::ast::FnBody::Block(vec![])),
                resolution: None,
            }],
            fn_auto_memo: HashSet::new(),
            fn_memo_qual: HashMap::new(),
            fn_auto_tco: HashSet::new(),
            fn_recursive_callsites: HashMap::new(),
            fn_recursive_scc_id: HashMap::new(),
            fn_specs: HashMap::new(),
            fn_direct_calls: HashMap::new(),
            type_defs: vec![],
            effect_sets: vec![],
            verify_blocks: vec![],
            verify_counts: HashMap::new(),
            verify_samples: HashMap::new(),
            decisions: vec![],
        };

        let out = format_context_json(&[ctx], "examples/main.av", None);
        assert!(!out.contains("\"module\": null"));
        assert!(!out.contains("\"functions\": []"));
        assert!(!out.contains("\"decisions\": []"));
    }

    #[test]
    fn json_context_renders_selection_metadata() {
        let selection = ContextSelection {
            depth_mode: "auto".to_string(),
            budget_bytes: Some(10 * 1024),
            included_depth: Some(1),
            next_depth: Some(2),
            next_used_bytes: Some(22424),
            truncated: true,
            used_bytes: 1779,
            focus_symbol: Some("Json.fromString".to_string()),
        };
        let out = format_context_json(
            &[file_context_with_spec()],
            "examples/spec.av",
            Some(&selection),
        );
        assert!(out.contains("\"selection\": {"));
        assert!(out.contains("\"depth_mode\": \"auto\""));
        assert!(out.contains("\"budget_bytes\": 10240"));
        assert!(out.contains("\"included_depth\": 1"));
        assert!(out.contains("\"next_depth\": 2"));
        assert!(out.contains("\"next_used_bytes\": 22424"));
        assert!(out.contains("\"focus_symbol\": \"Json.fromString\""));
        assert!(out.contains("\"truncated\": true"));
        assert!(out.contains("\"used_bytes\": 1779"));
    }
}
