//! The proof kernel written in Aver (`tools/proof-kernel/`), compiled to
//! Rust and embedded, so `aver proof --backend aver` checks step scripts in
//! process. `aver_generated/` and `runtime_support.rs` are generated by
//! `tools/regenerate_proof_kernel.py` and must not be edited by hand; this
//! file is the only interface.
#![allow(
    clippy::all,
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unused_parens,
    unused_braces,
    non_snake_case,
    non_camel_case_types,
    unreachable_patterns,
    hidden_glob_reexports
)]

pub use ::aver_rt::AverMap as HashMap;
pub use ::aver_rt::AverStr;
pub use ::aver_rt::Buffer;
pub use ::aver_rt::ByteBuilder;

mod runtime_support;
pub use runtime_support::*;

pub mod aver_generated;

/// The kernel's verdict on one serialised step script
/// (`crate::ir::proof_steps::sexpr`): the key of the law it proves, or the
/// refusal of its first wrong step (`step <path>: <reason>`).
pub fn verdict(script: &str) -> Result<String, String> {
    aver_generated::entry::verdict(AverStr::from(script))
        .map(|key| key.to_string())
        .map_err(|why| why.to_string())
}
