//! Facts about the builtins: equations stated directly over builtin calls
//! with untyped variables, each proved by steps from the wall rules.
//!
//! A law cites a fact by its key in `using` (`List.concat.assoc`), like a
//! law of its own program. A citation carries the fact's whole step proof
//! ([`super::LawRef::fact`]), and the kernel checks that proof before it
//! lets a step use the fact, so a fact is never an assumption. Lean
//! states each fact once, for every element type (`{α : Type}`), from the
//! same terms, and proves it with the same steps.
//!
//! The `List.` prefix of a `using` name is reserved for these facts: a
//! user module named `List` is already refused.

use crate::ast::{BinOp, Type};

use super::term::{self, Term, binop, builtin, var};
use super::{LawRef, Obligation, Proof, Script, WallRule};

/// What a given of a fact ranges over. A fact holds for every element,
/// key and value type, so a given has no Aver type, only this.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Sort {
    /// A list of any element type.
    List,
    /// A map of any key and value types.
    Map,
    /// A key of that map.
    Key,
    /// A value of that map.
    Value,
    /// A vector of any element type.
    Vector,
    /// An element of that vector (or list).
    Elem,
    /// An Int, such as an index.
    Int,
}

/// One fact: its key in `using`, its Lean theorem name, what each given
/// ranges over, and its script.
#[derive(Debug, Clone, PartialEq)]
pub struct Fact {
    pub key: &'static str,
    pub lean: &'static str,
    pub sorts: Vec<(String, Sort)>,
    pub script: Script,
}

impl Fact {
    /// The fact as a law a script cites, with its proof.
    pub fn law_ref(&self) -> LawRef {
        let ob = &self.script.obligation;
        LawRef {
            key: self.key.to_string(),
            givens: ob.givens.clone(),
            premise: ob.premise.clone(),
            lhs: ob.lhs.clone(),
            rhs: ob.rhs.clone(),
            fact: Some(Box::new(self.script.clone())),
        }
    }
}

impl Fact {
    /// The statement as an Aver law claim: `lhs => rhs`.
    pub fn claim(&self) -> String {
        let ob = &self.script.obligation;
        let show = |t: &Term| super::show::term(t, &super::sexpr::BuiltinsOnly);
        format!("{} => {}", show(&ob.lhs), show(&ob.rhs))
    }

    /// The facts its proof cites.
    pub fn cites(&self) -> Vec<String> {
        self.script.laws.iter().map(|l| l.key.clone()).collect()
    }

    /// Its `when`, written as Aver, if it has one.
    pub fn when(&self) -> Option<String> {
        let show = |t: &Term| super::show::term(t, &super::sexpr::BuiltinsOnly);
        self.script.obligation.premise.as_ref().map(show)
    }

    /// Whether every given is a list.
    pub fn over_lists(&self) -> bool {
        self.sorts.iter().all(|(_, s)| *s == Sort::List)
    }
}

/// The facts whose key starts with `prefix`, as Markdown: one entry per
/// fact with its statement as an Aver law. `docs/builtin-facts.md` is this
/// text for every fact.
pub fn markdown(prefix: &str) -> String {
    let mut out = String::from(
        "# Builtin facts\n\n<!-- Generated by `aver facts --markdown > docs/builtin-facts.md`; edit `src/ir/proof_steps/facts.rs`, not this file. -->\n\nA law cites a builtin fact by name in `using`, as it cites a law of its own program. Each fact holds for lists and vectors of every element type, and for maps of every key and value type, so its givens have no type here: `a`, `b`, `c` and `l` are lists, `n` an Int count, `m` a map, `k` and `k2` its keys and `v` its value; in a `Vector.` fact `v` is a vector, `i` and `j` are indices and `x` an element. The proof of each fact is written as steps and travels with every citation: the kernel written in Aver checks it before the law may use the fact, and Lean states the fact once, for every element type, and proves it with the same steps. When the steps stop at a term a fact's left side matches, `aver proof` names the fact in a hint. `aver facts` prints this list.\n",
    );
    for fact in all().iter().filter(|f| f.key.starts_with(prefix)) {
        let when = fact
            .when()
            .map(|w| format!("when {w}\n"))
            .unwrap_or_default();
        out.push_str(&format!(
            "\n## `{}`\n\n```aver\ngiven {}\n{when}{}\n```\n",
            fact.key,
            fact.script.obligation.givens.join(", "),
            fact.claim()
        ));
        let cites = fact.cites();
        if !cites.is_empty() {
            out.push_str(&format!(
                "\nProved from {}.\n",
                cites
                    .iter()
                    .map(|c| format!("`{c}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }
    out
}

/// Whether `name` is in the namespace reserved for facts.
pub fn is_fact_name(name: &str) -> bool {
    name.starts_with("List.") || name.starts_with("Map.") || name.starts_with("Vector.")
}

pub fn named(key: &str) -> Option<Fact> {
    all().into_iter().find(|f| f.key == key)
}

/// Every fact, each after the facts its proof cites.
pub fn all() -> Vec<Fact> {
    vec![
        len_of_concat(),
        concat_assoc(),
        concat_right_identity(),
        len_nonneg(),
        take_of_concat(),
        drop_of_concat(),
        take_non_positive(),
        drop_non_positive(),
        concat_take_drop(),
        len_of_drop_at_most(),
        len_of_reverse(),
        reverse_of_concat(),
        reverse_involutive(),
        map_get_after_set(),
        map_get_after_set_other(),
        map_has_after_set(),
        map_len_after_set_present(),
        vector_to_list_of_list(),
        vector_len_as_list(),
        vector_len_of_list(),
        vector_get_after_set(),
        vector_get_after_set_other(),
        vector_len_after_set(),
        vector_get_below_zero(),
        vector_get_past_end(),
    ]
}

fn len(l: Term) -> Term {
    builtin("List.len", vec![l], Some(Type::Int))
}

fn concat(a: Term, b: Term) -> Term {
    builtin("List.concat", vec![a, b], None)
}

fn cell(x: Term, t: Term) -> Term {
    builtin("List.prepend", vec![x, t], None)
}

fn add(a: Term, b: Term) -> Term {
    binop(BinOp::Add, a, b)
}

fn one() -> Term {
    term::int(&1.into())
}

fn rule(rule: WallRule, subst: Vec<(&str, Term)>) -> Proof {
    Proof::Rule {
        rule,
        subst: subst.into_iter().map(|(k, v)| (k.to_string(), v)).collect(),
        premises: Vec::new(),
    }
}

fn symm(p: Proof) -> Proof {
    Proof::Symm(Box::new(p))
}

fn congr(ctx: Term, inner: Proof) -> Proof {
    Proof::Congr {
        ctx,
        inner: Box::new(inner),
    }
}

fn trans(terms: Vec<Term>, steps: Vec<Proof>) -> Proof {
    Proof::Trans { terms, steps }
}

/// A fact over list givens, proved by induction on `on`; the cell case
/// names its parts `x` and `t` and its hypothesis `ih`.
#[allow(clippy::too_many_arguments)]
fn by_list_induction(
    key: &'static str,
    lean: &'static str,
    givens: &[&str],
    lhs: Term,
    rhs: Term,
    nil: Proof,
    cons: Proof,
    uses: &[Fact],
) -> Fact {
    let givens: Vec<String> = givens.iter().map(|g| g.to_string()).collect();
    Fact {
        key,
        lean,
        sorts: givens.iter().map(|g| (g.clone(), Sort::List)).collect(),
        script: Script {
            obligation: Obligation {
                key: key.to_string(),
                givens: givens.clone(),
                finite: Vec::new(),
                lists: givens,
                ints: Vec::new(),
                premise: None,
                lhs: lhs.clone(),
                rhs: rhs.clone(),
            },
            defs: Vec::new(),
            consts: Vec::new(),
            laws: uses.iter().map(Fact::law_ref).collect(),
            proof: Proof::InductList {
                var: "a".into(),
                lhs,
                rhs,
                nil: Box::new(nil),
                head: "x".into(),
                tail: "t".into(),
                general: Vec::new(),
                ihs: vec![super::IhAt {
                    name: "ih".into(),
                    at: Vec::new(),
                    carry: Vec::new(),
                }],
                cons: Box::new(cons),
            },
        },
    }
}

/// `List.len(List.concat(a, b)) = List.len(a) + List.len(b)`.
fn len_of_concat() -> Fact {
    let (a, b, x, t) = (|| var("a"), || var("b"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = trans(
        vec![
            len(concat(nil(), b())),
            len(b()),
            add(term::int(&0.into()), len(b())),
            add(len(nil()), len(b())),
        ],
        vec![
            congr(
                len(term::hole()),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            symm(rule(WallRule::ZeroAdd, vec![("a", len(b()))])),
            congr(
                add(term::hole(), len(b())),
                symm(rule(WallRule::LenNil, vec![])),
            ),
        ],
    );
    let step = trans(
        vec![
            len(concat(cell(x(), t()), b())),
            len(cell(x(), concat(t(), b()))),
            add(len(concat(t(), b())), one()),
            add(add(len(t()), len(b())), one()),
            add(add(len(t()), one()), len(b())),
            add(len(cell(x(), t())), len(b())),
        ],
        vec![
            congr(
                len(term::hole()),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            rule(WallRule::LenCons, vec![("x", x()), ("a", concat(t(), b()))]),
            congr(add(term::hole(), one()), Proof::Hyp("ih".into())),
            Proof::Ring {
                lhs: add(add(len(t()), len(b())), one()),
                rhs: add(add(len(t()), one()), len(b())),
            },
            congr(
                add(term::hole(), len(b())),
                symm(rule(WallRule::LenCons, vec![("x", x()), ("a", t())])),
            ),
        ],
    );
    by_list_induction(
        "List.len.ofConcat",
        "list_len_ofConcat",
        &["a", "b"],
        len(concat(a(), b())),
        add(len(a()), len(b())),
        base,
        step,
        &[],
    )
}

/// `List.concat(List.concat(a, b), c) = List.concat(a, List.concat(b, c))`.
fn concat_assoc() -> Fact {
    let (a, b, c, x, t) = (
        || var("a"),
        || var("b"),
        || var("c"),
        || var("x"),
        || var("t"),
    );
    let nil = term::nil;
    let base = trans(
        vec![
            concat(concat(nil(), b()), c()),
            concat(b(), c()),
            concat(nil(), concat(b(), c())),
        ],
        vec![
            congr(
                concat(term::hole(), c()),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            symm(rule(WallRule::ConcatNil, vec![("b", concat(b(), c()))])),
        ],
    );
    let step = trans(
        vec![
            concat(concat(cell(x(), t()), b()), c()),
            concat(cell(x(), concat(t(), b())), c()),
            cell(x(), concat(concat(t(), b()), c())),
            cell(x(), concat(t(), concat(b(), c()))),
            concat(cell(x(), t()), concat(b(), c())),
        ],
        vec![
            congr(
                concat(term::hole(), c()),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            rule(
                WallRule::ConcatCons,
                vec![("x", x()), ("a", concat(t(), b())), ("b", c())],
            ),
            congr(cell(x(), term::hole()), Proof::Hyp("ih".into())),
            symm(rule(
                WallRule::ConcatCons,
                vec![("x", x()), ("a", t()), ("b", concat(b(), c()))],
            )),
        ],
    );
    by_list_induction(
        "List.concat.assoc",
        "list_concat_assoc",
        &["a", "b", "c"],
        concat(concat(a(), b()), c()),
        concat(a(), concat(b(), c())),
        base,
        step,
        &[],
    )
}

fn reverse(l: Term) -> Term {
    builtin("List.reverse", vec![l], None)
}

fn take(l: Term, n: Term) -> Term {
    builtin("List.take", vec![l, n], None)
}

fn drop(l: Term, n: Term) -> Term {
    builtin("List.drop", vec![l, n], None)
}

fn single(x: Term) -> Term {
    cell(x, term::nil())
}

fn zero() -> Term {
    term::int(&0.into())
}

/// An earlier fact at explicit arguments.
fn cite(fact: &Fact, args: Vec<Term>) -> Proof {
    Proof::Law {
        law: fact.key.to_string(),
        subst: fact
            .script
            .obligation
            .givens
            .iter()
            .cloned()
            .zip(args)
            .collect(),
        premise: None,
    }
}

/// `n > 0` decided `true` from `List.len(l) >= 0`: split on that
/// comparison, settle the goal linearly when it holds, and refute the other
/// case with `List.len.nonneg`.
fn positive_from_len(goal: Term, l: Term, h: &str) -> Proof {
    use super::linear;
    let known = binop(BinOp::Gte, len(l.clone()), zero());
    let mut atoms = Vec::new();
    let facts = vec![
        linear::as_nonneg(&goal, false, &mut atoms).expect("an Int comparison"),
        linear::as_nonneg(&known, true, &mut atoms).expect("an Int comparison"),
    ];
    let weights = linear::certificate(&facts).expect("the goal follows linearly");
    Proof::Cases {
        on: known.clone(),
        hyp: h.to_string(),
        if_true: Box::new(Proof::Linear {
            goal: goal.clone(),
            value: true,
            hyps: vec![h.to_string()],
            weights,
        }),
        if_false: Box::new(Proof::Absurd {
            contradiction: Box::new(trans(
                vec![term::boolean(true), known, term::boolean(false)],
                vec![
                    symm(cite(&len_nonneg(), vec![l])),
                    Proof::Hyp(h.to_string()),
                ],
            )),
            lhs: goal,
            rhs: term::boolean(true),
        }),
    }
}

/// `f(l, 0) = want` for every list `l`, by induction on `l`: `[]` by the
/// empty-list rule, a cell by the rule for a count at or below zero.
fn at_zero(
    f: fn(Term, Term) -> Term,
    l: &str,
    want: fn(Term) -> Term,
    nil_rule: WallRule,
    le_rule: WallRule,
) -> Proof {
    let (x, t) = (|| var("x2"), || var("t2"));
    Proof::InductList {
        var: l.to_string(),
        lhs: f(var(l), zero()),
        rhs: want(var(l)),
        nil: Box::new(rule(nil_rule, vec![("n", zero())])),
        head: "x2".into(),
        tail: "t2".into(),
        general: Vec::new(),
        ihs: Vec::new(),
        cons: Box::new(Proof::Rule {
            rule: le_rule,
            subst: vec![("x".into(), x()), ("a".into(), t()), ("n".into(), zero())],
            premises: vec![Proof::Compute {
                lhs: binop(BinOp::Lte, zero(), zero()),
                rhs: term::boolean(true),
            }],
        }),
    }
}

/// `List.concat(a, []) = a`.
fn concat_right_identity() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nil = term::nil;
    by_list_induction(
        "List.concat.rightIdentity",
        "list_concat_rightIdentity",
        &["a"],
        concat(a(), nil()),
        a(),
        rule(WallRule::ConcatNil, vec![("b", nil())]),
        trans(
            vec![
                concat(cell(x(), t()), nil()),
                cell(x(), concat(t(), nil())),
                cell(x(), t()),
            ],
            vec![
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", nil())],
                ),
                congr(cell(x(), term::hole()), Proof::Hyp("ih".into())),
            ],
        ),
        &[],
    )
}

/// `List.len(a) >= 0` is `true`.
fn len_nonneg() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nonneg = |l: Term| binop(BinOp::Gte, l, zero());
    let goal = nonneg(add(len(t()), one()));
    let mut atoms = Vec::new();
    let weights = super::linear::certificate(&[
        super::linear::as_nonneg(&goal, false, &mut atoms).expect("comparison"),
        super::linear::as_nonneg(&nonneg(len(t())), true, &mut atoms).expect("comparison"),
    ])
    .expect("linear");
    by_list_induction(
        "List.len.nonneg",
        "list_len_nonneg",
        &["a"],
        nonneg(len(a())),
        term::boolean(true),
        // Through `0 >= 0`: Lean decides only a closed statement, and an
        // empty list of some element type is not one.
        trans(
            vec![
                nonneg(len(term::nil())),
                nonneg(zero()),
                term::boolean(true),
            ],
            vec![
                congr(nonneg(term::hole()), rule(WallRule::LenNil, vec![])),
                Proof::Compute {
                    lhs: nonneg(zero()),
                    rhs: term::boolean(true),
                },
            ],
        ),
        trans(
            vec![
                nonneg(len(cell(x(), t()))),
                goal.clone(),
                term::boolean(true),
            ],
            vec![
                congr(
                    nonneg(term::hole()),
                    rule(WallRule::LenCons, vec![("x", x()), ("a", t())]),
                ),
                Proof::Linear {
                    goal,
                    value: true,
                    hyps: vec!["ih".into()],
                    weights,
                },
            ],
        ),
        &[],
    )
}

/// The cell case shared by `take` and `drop` of a concatenation at the
/// length of its first part: open the cell, step past it, then the
/// hypothesis.
fn sliced_cell(
    slice: fn(Term, Term) -> Term,
    gt_rule: WallRule,
    after: fn(Term, Term) -> Term,
    result: Term,
) -> Proof {
    let (b, x, t) = (|| var("b"), || var("x"), || var("t"));
    let n1 = || add(len(t()), one());
    let ctb = || concat(t(), b());
    trans(
        vec![
            slice(concat(cell(x(), t()), b()), len(cell(x(), t()))),
            slice(cell(x(), ctb()), len(cell(x(), t()))),
            slice(cell(x(), ctb()), n1()),
            after(x(), slice(ctb(), binop(BinOp::Sub, n1(), one()))),
            after(x(), slice(ctb(), len(t()))),
            after(x(), result),
        ],
        vec![
            congr(
                slice(term::hole(), len(cell(x(), t()))),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            congr(
                slice(cell(x(), ctb()), term::hole()),
                rule(WallRule::LenCons, vec![("x", x()), ("a", t())]),
            ),
            Proof::Rule {
                rule: gt_rule,
                subst: vec![("x".into(), x()), ("a".into(), ctb()), ("n".into(), n1())],
                premises: vec![positive_from_len(
                    binop(BinOp::Gt, n1(), zero()),
                    t(),
                    "h_len",
                )],
            },
            congr(
                after(x(), slice(ctb(), term::hole())),
                Proof::Ring {
                    lhs: binop(BinOp::Sub, n1(), one()),
                    rhs: len(t()),
                },
            ),
            congr(after(x(), term::hole()), Proof::Hyp("ih".into())),
        ],
    )
}

/// `List.take(List.concat(a, b), List.len(a)) = a`.
fn take_of_concat() -> Fact {
    let (a, b) = (|| var("a"), || var("b"));
    let nil = term::nil;
    let base = trans(
        vec![
            take(concat(nil(), b()), len(nil())),
            take(b(), len(nil())),
            take(b(), zero()),
            nil(),
        ],
        vec![
            congr(
                take(term::hole(), len(nil())),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            congr(take(b(), term::hole()), rule(WallRule::LenNil, vec![])),
            at_zero(
                take,
                "b",
                |_| term::nil(),
                WallRule::TakeNil,
                WallRule::TakeConsLe,
            ),
        ],
    );
    by_list_induction(
        "List.take.ofConcat",
        "list_take_ofConcat",
        &["a", "b"],
        take(concat(a(), b()), len(a())),
        a(),
        base,
        sliced_cell(take, WallRule::TakeConsGt, cell, var("t")),
        &[len_nonneg()],
    )
}

/// `List.drop(List.concat(a, b), List.len(a)) = b`.
fn drop_of_concat() -> Fact {
    let (a, b) = (|| var("a"), || var("b"));
    let nil = term::nil;
    let base = trans(
        vec![
            drop(concat(nil(), b()), len(nil())),
            drop(b(), len(nil())),
            drop(b(), zero()),
            b(),
        ],
        vec![
            congr(
                drop(term::hole(), len(nil())),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            congr(drop(b(), term::hole()), rule(WallRule::LenNil, vec![])),
            at_zero(drop, "b", |l| l, WallRule::DropNil, WallRule::DropConsLe),
        ],
    );
    by_list_induction(
        "List.drop.ofConcat",
        "list_drop_ofConcat",
        &["a", "b"],
        drop(concat(a(), b()), len(a())),
        b(),
        base,
        sliced_cell(drop, WallRule::DropConsGt, |_, rest| rest, b()),
        &[len_nonneg()],
    )
}

/// `Proof::Linear` for `goal = true` from the hypotheses named, each
/// with the comparison it states and its value.
fn linear_from(goal: Term, hyps: &[(&str, Term, bool)]) -> Proof {
    use super::linear;
    let mut atoms = Vec::new();
    let mut facts = vec![linear::as_nonneg(&goal, false, &mut atoms).expect("an Int comparison")];
    for (_, t, v) in hyps {
        facts.push(linear::as_nonneg(t, *v, &mut atoms).expect("an Int comparison"));
    }
    Proof::Linear {
        goal,
        value: true,
        hyps: hyps.iter().map(|(n, _, _)| n.to_string()).collect(),
        weights: linear::certificate(&facts).expect("the goal follows linearly"),
    }
}

/// A rule on a list cell at count `n` whose premise is the hypothesis
/// `h : n <= 0 = true` (`positive` false), or `n > 0 = true` read from
/// `h : n <= 0 = false` (`positive` true).
fn counted_cell(rule: WallRule, x: Term, t: Term, n: Term, h: &str, positive: bool) -> Proof {
    let premise = if positive {
        Proof::Rule {
            rule: WallRule::GtOfNotLe,
            subst: vec![("a".into(), n.clone()), ("b".into(), zero())],
            premises: vec![Proof::Hyp(h.to_string())],
        }
    } else {
        Proof::Hyp(h.to_string())
    };
    Proof::Rule {
        rule,
        subst: vec![("x".into(), x), ("a".into(), t), ("n".into(), n)],
        premises: vec![premise],
    }
}

/// `when n <= 0`: `List.take(l, n) = []`, by cases on `l`.
fn take_non_positive() -> Fact {
    let (l, n, x, t) = (|| var("l"), || var("n"), || var("x"), || var("t"));
    vector_fact(
        "List.take.nonPositive",
        "list_take_nonPositive",
        &[("l", Sort::List), ("n", Sort::Int)],
        Some(binop(BinOp::Lte, n(), zero())),
        (take(l(), n()), term::nil()),
        Proof::InductList {
            var: "l".into(),
            lhs: take(l(), n()),
            rhs: term::nil(),
            nil: Box::new(rule(WallRule::TakeNil, vec![("n", n())])),
            head: "x".into(),
            tail: "t".into(),
            general: Vec::new(),
            ihs: Vec::new(),
            cons: Box::new(counted_cell(
                WallRule::TakeConsLe,
                x(),
                t(),
                n(),
                "when",
                false,
            )),
        },
        &[],
    )
}

/// `when n <= 0`: `List.drop(l, n) = l`, by cases on `l`.
fn drop_non_positive() -> Fact {
    let (l, n, x, t) = (|| var("l"), || var("n"), || var("x"), || var("t"));
    vector_fact(
        "List.drop.nonPositive",
        "list_drop_nonPositive",
        &[("l", Sort::List), ("n", Sort::Int)],
        Some(binop(BinOp::Lte, n(), zero())),
        (drop(l(), n()), l()),
        Proof::InductList {
            var: "l".into(),
            lhs: drop(l(), n()),
            rhs: l(),
            nil: Box::new(rule(WallRule::DropNil, vec![("n", n())])),
            head: "x".into(),
            tail: "t".into(),
            general: Vec::new(),
            ihs: Vec::new(),
            cons: Box::new(counted_cell(
                WallRule::DropConsLe,
                x(),
                t(),
                n(),
                "when",
                false,
            )),
        },
        &[],
    )
}

/// `List.concat(List.take(l, n), List.drop(l, n)) = l`, by induction on
/// `l` for every `n`: a cell splits on `n <= 0`, and above zero the tail
/// is split at `n - 1`.
fn concat_take_drop() -> Fact {
    let (l, n, x, t) = (|| var("l"), || var("n"), || var("x"), || var("t"));
    let nil = term::nil;
    let less = || binop(BinOp::Sub, n(), one());
    let xt = || cell(x(), t());
    let split = |l: Term, n: Term| concat(take(l.clone(), n.clone()), drop(l, n));
    let base = trans(
        vec![
            split(nil(), n()),
            concat(nil(), drop(nil(), n())),
            concat(nil(), nil()),
            nil(),
        ],
        vec![
            congr(
                concat(term::hole(), drop(nil(), n())),
                rule(WallRule::TakeNil, vec![("n", n())]),
            ),
            congr(
                concat(nil(), term::hole()),
                rule(WallRule::DropNil, vec![("n", n())]),
            ),
            rule(WallRule::ConcatNil, vec![("b", nil())]),
        ],
    );
    let at_most_zero = trans(
        vec![
            split(xt(), n()),
            concat(nil(), drop(xt(), n())),
            concat(nil(), xt()),
            xt(),
        ],
        vec![
            congr(
                concat(term::hole(), drop(xt(), n())),
                counted_cell(WallRule::TakeConsLe, x(), t(), n(), "h_le", false),
            ),
            congr(
                concat(nil(), term::hole()),
                counted_cell(WallRule::DropConsLe, x(), t(), n(), "h_le", false),
            ),
            rule(WallRule::ConcatNil, vec![("b", xt())]),
        ],
    );
    let above_zero = trans(
        vec![
            split(xt(), n()),
            concat(cell(x(), take(t(), less())), drop(xt(), n())),
            concat(cell(x(), take(t(), less())), drop(t(), less())),
            cell(x(), split(t(), less())),
            xt(),
        ],
        vec![
            congr(
                concat(term::hole(), drop(xt(), n())),
                counted_cell(WallRule::TakeConsGt, x(), t(), n(), "h_le", true),
            ),
            congr(
                concat(cell(x(), take(t(), less())), term::hole()),
                counted_cell(WallRule::DropConsGt, x(), t(), n(), "h_le", true),
            ),
            rule(
                WallRule::ConcatCons,
                vec![
                    ("x", x()),
                    ("a", take(t(), less())),
                    ("b", drop(t(), less())),
                ],
            ),
            congr(cell(x(), term::hole()), Proof::Hyp("ih".into())),
        ],
    );
    vector_fact(
        "List.concat.takeDrop",
        "list_concat_takeDrop",
        &[("l", Sort::List), ("n", Sort::Int)],
        None,
        (split(l(), n()), l()),
        Proof::InductList {
            var: "l".into(),
            lhs: split(l(), n()),
            rhs: l(),
            nil: Box::new(base),
            head: "x".into(),
            tail: "t".into(),
            general: vec!["n".into()],
            ihs: vec![super::IhAt {
                name: "ih".into(),
                at: vec![less()],
                carry: Vec::new(),
            }],
            cons: Box::new(Proof::Cases {
                on: binop(BinOp::Lte, n(), zero()),
                hyp: "h_le".into(),
                if_true: Box::new(at_most_zero),
                if_false: Box::new(above_zero),
            }),
        },
        &[],
    )
}

/// `List.len(List.drop(l, n)) <= List.len(l)`, by induction on `l` for
/// every `n`.
fn len_of_drop_at_most() -> Fact {
    let (l, n, x, t) = (|| var("l"), || var("n"), || var("x"), || var("t"));
    let nil = term::nil;
    let less = || binop(BinOp::Sub, n(), one());
    let xt = || cell(x(), t());
    let at_most = |l: Term, n: Term| binop(BinOp::Lte, len(drop(l.clone(), n)), len(l));
    let base = trans(
        vec![
            at_most(nil(), n()),
            binop(BinOp::Lte, len(nil()), len(nil())),
            binop(BinOp::Lte, zero(), len(nil())),
            binop(BinOp::Lte, zero(), zero()),
            term::boolean(true),
        ],
        vec![
            congr(
                binop(BinOp::Lte, len(term::hole()), len(nil())),
                rule(WallRule::DropNil, vec![("n", n())]),
            ),
            congr(
                binop(BinOp::Lte, term::hole(), len(nil())),
                rule(WallRule::LenNil, vec![]),
            ),
            congr(
                binop(BinOp::Lte, zero(), term::hole()),
                rule(WallRule::LenNil, vec![]),
            ),
            Proof::Compute {
                lhs: binop(BinOp::Lte, zero(), zero()),
                rhs: term::boolean(true),
            },
        ],
    );
    let same = binop(BinOp::Lte, len(xt()), len(xt()));
    let at_most_zero = trans(
        vec![at_most(xt(), n()), same.clone(), term::boolean(true)],
        vec![
            congr(
                binop(BinOp::Lte, len(term::hole()), len(xt())),
                counted_cell(WallRule::DropConsLe, x(), t(), n(), "h_le", false),
            ),
            linear_from(same, &[]),
        ],
    );
    let shorter = binop(BinOp::Lte, len(drop(t(), less())), add(len(t()), one()));
    let above_zero = trans(
        vec![
            at_most(xt(), n()),
            binop(BinOp::Lte, len(drop(t(), less())), len(xt())),
            shorter.clone(),
            term::boolean(true),
        ],
        vec![
            congr(
                binop(BinOp::Lte, len(term::hole()), len(xt())),
                counted_cell(WallRule::DropConsGt, x(), t(), n(), "h_le", true),
            ),
            congr(
                binop(BinOp::Lte, len(drop(t(), less())), term::hole()),
                rule(WallRule::LenCons, vec![("x", x()), ("a", t())]),
            ),
            linear_from(shorter, &[("ih", at_most(t(), less()), true)]),
        ],
    );
    vector_fact(
        "List.len.ofDropAtMost",
        "list_len_ofDropAtMost",
        &[("l", Sort::List), ("n", Sort::Int)],
        None,
        (at_most(l(), n()), term::boolean(true)),
        Proof::InductList {
            var: "l".into(),
            lhs: at_most(l(), n()),
            rhs: term::boolean(true),
            nil: Box::new(base),
            head: "x".into(),
            tail: "t".into(),
            general: vec!["n".into()],
            ihs: vec![super::IhAt {
                name: "ih".into(),
                at: vec![less()],
                carry: Vec::new(),
            }],
            cons: Box::new(Proof::Cases {
                on: binop(BinOp::Lte, n(), zero()),
                hyp: "h_le".into(),
                if_true: Box::new(at_most_zero),
                if_false: Box::new(above_zero),
            }),
        },
        &[],
    )
}

/// `List.len(List.reverse(a)) = List.len(a)`.
fn len_of_reverse() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = congr(len(term::hole()), rule(WallRule::ReverseNil, vec![]));
    let step = trans(
        vec![
            len(reverse(cell(x(), t()))),
            len(concat(reverse(t()), single(x()))),
            add(len(reverse(t())), len(single(x()))),
            add(len(t()), len(single(x()))),
            add(len(t()), add(len(nil()), one())),
            add(len(t()), add(zero(), one())),
            add(len(t()), one()),
            len(cell(x(), t())),
        ],
        vec![
            congr(
                len(term::hole()),
                rule(WallRule::ReverseCons, vec![("x", x()), ("a", t())]),
            ),
            cite(&len_of_concat(), vec![reverse(t()), single(x())]),
            congr(add(term::hole(), len(single(x()))), Proof::Hyp("ih".into())),
            congr(
                add(len(t()), term::hole()),
                rule(WallRule::LenCons, vec![("x", x()), ("a", nil())]),
            ),
            congr(
                add(len(t()), add(term::hole(), one())),
                rule(WallRule::LenNil, vec![]),
            ),
            Proof::Ring {
                lhs: add(len(t()), add(zero(), one())),
                rhs: add(len(t()), one()),
            },
            symm(rule(WallRule::LenCons, vec![("x", x()), ("a", t())])),
        ],
    );
    by_list_induction(
        "List.len.ofReverse",
        "list_len_ofReverse",
        &["a"],
        len(reverse(a())),
        len(a()),
        base,
        step,
        &[len_of_concat()],
    )
}

/// `List.reverse(List.concat(a, b)) = List.concat(List.reverse(b), List.reverse(a))`.
fn reverse_of_concat() -> Fact {
    let (a, b, x, t) = (|| var("a"), || var("b"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = trans(
        vec![
            reverse(concat(nil(), b())),
            reverse(b()),
            concat(reverse(b()), nil()),
            concat(reverse(b()), reverse(nil())),
        ],
        vec![
            congr(
                reverse(term::hole()),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            symm(cite(&concat_right_identity(), vec![reverse(b())])),
            congr(
                concat(reverse(b()), term::hole()),
                symm(rule(WallRule::ReverseNil, vec![])),
            ),
        ],
    );
    let step = trans(
        vec![
            reverse(concat(cell(x(), t()), b())),
            reverse(cell(x(), concat(t(), b()))),
            concat(reverse(concat(t(), b())), single(x())),
            concat(concat(reverse(b()), reverse(t())), single(x())),
            concat(reverse(b()), concat(reverse(t()), single(x()))),
            concat(reverse(b()), reverse(cell(x(), t()))),
        ],
        vec![
            congr(
                reverse(term::hole()),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            rule(
                WallRule::ReverseCons,
                vec![("x", x()), ("a", concat(t(), b()))],
            ),
            congr(concat(term::hole(), single(x())), Proof::Hyp("ih".into())),
            cite(
                &concat_assoc(),
                vec![reverse(b()), reverse(t()), single(x())],
            ),
            congr(
                concat(reverse(b()), term::hole()),
                symm(rule(WallRule::ReverseCons, vec![("x", x()), ("a", t())])),
            ),
        ],
    );
    by_list_induction(
        "List.reverse.ofConcat",
        "list_reverse_ofConcat",
        &["a", "b"],
        reverse(concat(a(), b())),
        concat(reverse(b()), reverse(a())),
        base,
        step,
        &[concat_assoc(), concat_right_identity()],
    )
}

/// `List.reverse(List.reverse(a)) = a`.
fn reverse_involutive() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = trans(
        vec![reverse(reverse(nil())), reverse(nil()), nil()],
        vec![
            congr(reverse(term::hole()), rule(WallRule::ReverseNil, vec![])),
            rule(WallRule::ReverseNil, vec![]),
        ],
    );
    let step = trans(
        vec![
            reverse(reverse(cell(x(), t()))),
            reverse(concat(reverse(t()), single(x()))),
            concat(reverse(single(x())), reverse(reverse(t()))),
            concat(reverse(single(x())), t()),
            concat(concat(reverse(nil()), single(x())), t()),
            concat(concat(nil(), single(x())), t()),
            concat(single(x()), t()),
            cell(x(), concat(nil(), t())),
            cell(x(), t()),
        ],
        vec![
            congr(
                reverse(term::hole()),
                rule(WallRule::ReverseCons, vec![("x", x()), ("a", t())]),
            ),
            cite(&reverse_of_concat(), vec![reverse(t()), single(x())]),
            congr(
                concat(reverse(single(x())), term::hole()),
                Proof::Hyp("ih".into()),
            ),
            congr(
                concat(term::hole(), t()),
                rule(WallRule::ReverseCons, vec![("x", x()), ("a", nil())]),
            ),
            congr(
                concat(concat(term::hole(), single(x())), t()),
                rule(WallRule::ReverseNil, vec![]),
            ),
            congr(
                concat(term::hole(), t()),
                rule(WallRule::ConcatNil, vec![("b", single(x()))]),
            ),
            rule(
                WallRule::ConcatCons,
                vec![("x", x()), ("a", nil()), ("b", t())],
            ),
            congr(
                cell(x(), term::hole()),
                rule(WallRule::ConcatNil, vec![("b", t())]),
            ),
        ],
    );
    by_list_induction(
        "List.reverse.involutive",
        "list_reverse_involutive",
        &["a"],
        reverse(reverse(a())),
        a(),
        base,
        step,
        &[reverse_of_concat()],
    )
}

fn map_set(m: Term, k: Term, v: Term) -> Term {
    builtin("Map.set", vec![m, k, v], None)
}

fn map_get(m: Term, k: Term) -> Term {
    builtin("Map.get", vec![m, k], None)
}

fn map_has(m: Term, k: Term) -> Term {
    builtin("Map.has", vec![m, k], Some(Type::Bool))
}

/// A fact about maps, proved by one rule: `m` a map, `k` and `k2` keys, `v`
/// a value; `when` is the law's own premise, proved by `Hyp("when")`.
fn map_fact(
    key: &'static str,
    lean: &'static str,
    givens: &[&str],
    premise: Option<Term>,
    lhs: Term,
    rhs: Term,
    proof: Proof,
) -> Fact {
    let sort = |g: &str| match g {
        "m" => Sort::Map,
        "v" => Sort::Value,
        _ => Sort::Key,
    };
    Fact {
        key,
        lean,
        sorts: givens.iter().map(|g| (g.to_string(), sort(g))).collect(),
        script: Script {
            obligation: Obligation {
                key: key.to_string(),
                givens: givens.iter().map(|g| g.to_string()).collect(),
                finite: Vec::new(),
                lists: Vec::new(),
                ints: Vec::new(),
                premise,
                lhs,
                rhs,
            },
            defs: Vec::new(),
            consts: Vec::new(),
            laws: Vec::new(),
            proof,
        },
    }
}

fn mkv() -> (Term, Term, Term) {
    (var("m"), var("k"), var("v"))
}

/// `Map.get(Map.set(m, k, v), k) = Option.Some(v)`.
fn map_get_after_set() -> Fact {
    let (m, k, v) = mkv();
    let some = crate::ast::Spanned::bare(crate::ir::hir::ResolvedExpr::Ctor(
        crate::ir::hir::ResolvedCtor::Builtin(crate::ir::hir::BuiltinCtor::OptionSome),
        vec![v.clone()],
    ));
    map_fact(
        "Map.get.afterSet",
        "map_get_afterSet",
        &["m", "k", "v"],
        None,
        map_get(map_set(m.clone(), k.clone(), v.clone()), k.clone()),
        some,
        rule(WallRule::MapGetSetSame, vec![("m", m), ("k", k), ("v", v)]),
    )
}

/// `when k != k2`: `Map.get(Map.set(m, k, v), k2) = Map.get(m, k2)`.
fn map_get_after_set_other() -> Fact {
    let (m, k, v) = mkv();
    let k2 = var("k2");
    map_fact(
        "Map.get.afterSetOther",
        "map_get_afterSetOther",
        &["m", "k", "v", "k2"],
        Some(binop(BinOp::Neq, k.clone(), k2.clone())),
        map_get(map_set(m.clone(), k.clone(), v.clone()), k2.clone()),
        map_get(m.clone(), k2.clone()),
        Proof::Rule {
            rule: WallRule::MapGetSetOther,
            subst: vec![
                ("m".into(), m),
                ("k".into(), k),
                ("v".into(), v),
                ("k2".into(), k2),
            ],
            premises: vec![Proof::Hyp("when".into())],
        },
    )
}

/// `Map.has(Map.set(m, k, v), k) = true`.
fn map_has_after_set() -> Fact {
    let (m, k, v) = mkv();
    map_fact(
        "Map.has.afterSet",
        "map_has_afterSet",
        &["m", "k", "v"],
        None,
        map_has(map_set(m.clone(), k.clone(), v.clone()), k.clone()),
        term::boolean(true),
        rule(WallRule::MapHasSetSame, vec![("m", m), ("k", k), ("v", v)]),
    )
}

/// `when Map.has(m, k)`: `Map.len(Map.set(m, k, v)) = Map.len(m)`.
fn map_len_after_set_present() -> Fact {
    let (m, k, v) = mkv();
    let size = |t: Term| builtin("Map.len", vec![t], Some(Type::Int));
    map_fact(
        "Map.len.afterSetPresent",
        "map_len_afterSetPresent",
        &["m", "k", "v"],
        Some(map_has(m.clone(), k.clone())),
        size(map_set(m.clone(), k.clone(), v.clone())),
        size(m.clone()),
        Proof::Rule {
            rule: WallRule::MapLenSetPresent,
            subst: vec![("m".into(), m), ("k".into(), k), ("v".into(), v)],
            premises: vec![Proof::Hyp("when".into())],
        },
    )
}

/// A fact about vectors: each given with what it ranges over; `when` is
/// the law's own premise, proved by `Hyp("when")`.
fn vector_fact(
    key: &'static str,
    lean: &'static str,
    sorts: &[(&str, Sort)],
    premise: Option<Term>,
    eq: (Term, Term),
    proof: Proof,
    uses: &[Fact],
) -> Fact {
    let givens: Vec<String> = sorts.iter().map(|(g, _)| g.to_string()).collect();
    Fact {
        key,
        lean,
        sorts: sorts.iter().map(|(g, s)| (g.to_string(), *s)).collect(),
        script: Script {
            obligation: Obligation {
                key: key.to_string(),
                givens,
                finite: Vec::new(),
                lists: sorts
                    .iter()
                    .filter(|(_, s)| *s == Sort::List)
                    .map(|(g, _)| g.to_string())
                    .collect(),
                ints: Vec::new(),
                premise,
                lhs: eq.0,
                rhs: eq.1,
            },
            defs: Vec::new(),
            consts: Vec::new(),
            laws: uses.iter().map(Fact::law_ref).collect(),
            proof,
        },
    }
}

fn vlen(v: Term) -> Term {
    builtin("Vector.len", vec![v], Some(Type::Int))
}

fn vget(v: Term, i: Term) -> Term {
    builtin("Vector.get", vec![v, i], None)
}

fn from_list(l: Term) -> Term {
    builtin("Vector.fromList", vec![l], None)
}

fn to_list(v: Term) -> Term {
    builtin("List.fromVector", vec![v], None)
}

/// `Option.withDefault(Vector.set(v, i, x), v)`: the vector after a write,
/// or `v` when `i` is out of range.
fn written(v: Term, i: Term, x: Term) -> Term {
    builtin(
        "Option.withDefault",
        vec![builtin("Vector.set", vec![v.clone(), i, x], None), v],
        None,
    )
}

fn in_range(i: Term, v: Term) -> Term {
    term::bool_and(
        binop(BinOp::Lte, term::int(&0.into()), i.clone()),
        binop(BinOp::Lt, i, vlen(v)),
    )
}

fn option(c: crate::ir::hir::BuiltinCtor, args: Vec<Term>) -> Term {
    crate::ast::Spanned::bare(crate::ir::hir::ResolvedExpr::Ctor(
        crate::ir::hir::ResolvedCtor::Builtin(c),
        args,
    ))
}

/// `List.fromVector(Vector.fromList(l)) = l`.
fn vector_to_list_of_list() -> Fact {
    let l = || var("l");
    vector_fact(
        "Vector.toList.ofList",
        "vector_toList_ofList",
        &[("l", Sort::List)],
        None,
        (to_list(from_list(l())), l()),
        rule(WallRule::VecToListOfList, vec![("l", l())]),
        &[],
    )
}

/// `Vector.len(v) = List.len(List.fromVector(v))`.
fn vector_len_as_list() -> Fact {
    let v = || var("v");
    vector_fact(
        "Vector.len.asList",
        "vector_len_asList",
        &[("v", Sort::Vector)],
        None,
        (vlen(v()), len(to_list(v()))),
        rule(WallRule::VecLenToList, vec![("v", v())]),
        &[],
    )
}

/// `Vector.len(Vector.fromList(l)) = List.len(l)`.
fn vector_len_of_list() -> Fact {
    let l = || var("l");
    vector_fact(
        "Vector.len.ofList",
        "vector_len_ofList",
        &[("l", Sort::List)],
        None,
        (vlen(from_list(l())), len(l())),
        trans(
            vec![vlen(from_list(l())), len(to_list(from_list(l()))), len(l())],
            vec![
                rule(WallRule::VecLenToList, vec![("v", from_list(l()))]),
                congr(
                    len(term::hole()),
                    rule(WallRule::VecToListOfList, vec![("l", l())]),
                ),
            ],
        ),
        &[],
    )
}

/// `when Bool.and(0 <= i, i < Vector.len(v))`: a read at `i` after a write
/// at `i` is `Option.Some(x)`.
fn vector_get_after_set() -> Fact {
    let (v, i, x) = (|| var("v"), || var("i"), || var("x"));
    vector_fact(
        "Vector.get.afterSet",
        "vector_get_afterSet",
        &[("v", Sort::Vector), ("i", Sort::Int), ("x", Sort::Elem)],
        Some(in_range(i(), v())),
        (
            vget(written(v(), i(), x()), i()),
            option(crate::ir::hir::BuiltinCtor::OptionSome, vec![x()]),
        ),
        Proof::Rule {
            rule: WallRule::VecGetSetSame,
            subst: vec![("v".into(), v()), ("i".into(), i()), ("x".into(), x())],
            premises: vec![Proof::Hyp("when".into())],
        },
        &[],
    )
}

/// `when Bool.and(Bool.and(0 <= i, i < Vector.len(v)), i != j)`: a write at
/// `i` leaves index `j` as it was.
fn vector_get_after_set_other() -> Fact {
    let (v, i, x, j) = (|| var("v"), || var("i"), || var("x"), || var("j"));
    let ne = || binop(BinOp::Neq, i(), j());
    let elim = |rule: WallRule| Proof::Rule {
        rule,
        subst: vec![("a".into(), in_range(i(), v())), ("b".into(), ne())],
        premises: vec![Proof::Hyp("when".into())],
    };
    vector_fact(
        "Vector.get.afterSetOther",
        "vector_get_afterSetOther",
        &[
            ("v", Sort::Vector),
            ("i", Sort::Int),
            ("x", Sort::Elem),
            ("j", Sort::Int),
        ],
        Some(term::bool_and(in_range(i(), v()), ne())),
        (vget(written(v(), i(), x()), j()), vget(v(), j())),
        Proof::Rule {
            rule: WallRule::VecGetSetOther,
            subst: vec![
                ("v".into(), v()),
                ("i".into(), i()),
                ("x".into(), x()),
                ("j".into(), j()),
            ],
            premises: vec![elim(WallRule::AndElimL), elim(WallRule::AndElimR)],
        },
        &[],
    )
}

/// `Vector.len(Option.withDefault(Vector.set(v, i, x), v)) = Vector.len(v)`.
fn vector_len_after_set() -> Fact {
    let (v, i, x) = (|| var("v"), || var("i"), || var("x"));
    vector_fact(
        "Vector.len.afterSet",
        "vector_len_afterSet",
        &[("v", Sort::Vector), ("i", Sort::Int), ("x", Sort::Elem)],
        None,
        (vlen(written(v(), i(), x())), vlen(v())),
        rule(
            WallRule::VecLenSet,
            vec![("v", v()), ("i", i()), ("x", x())],
        ),
        &[],
    )
}

/// `when i < 0`: `Vector.get(v, i) = Option.None`.
fn vector_get_below_zero() -> Fact {
    let (v, i) = (|| var("v"), || var("i"));
    vector_fact(
        "Vector.get.belowZero",
        "vector_get_belowZero",
        &[("v", Sort::Vector), ("i", Sort::Int)],
        Some(binop(BinOp::Lt, i(), term::int(&0.into()))),
        (
            vget(v(), i()),
            option(crate::ir::hir::BuiltinCtor::OptionNone, vec![]),
        ),
        Proof::Rule {
            rule: WallRule::VecGetNegative,
            subst: vec![("v".into(), v()), ("i".into(), i())],
            premises: vec![Proof::Hyp("when".into())],
        },
        &[],
    )
}

/// `when i >= Vector.len(v)`: `Vector.get(v, i) = Option.None`.
fn vector_get_past_end() -> Fact {
    let (v, i) = (|| var("v"), || var("i"));
    vector_fact(
        "Vector.get.pastEnd",
        "vector_get_pastEnd",
        &[("v", Sort::Vector), ("i", Sort::Int)],
        Some(binop(BinOp::Gte, i(), vlen(v()))),
        (
            vget(v(), i()),
            option(crate::ir::hir::BuiltinCtor::OptionNone, vec![]),
        ),
        Proof::Rule {
            rule: WallRule::VecGetPastEnd,
            subst: vec![("v".into(), v()), ("i".into(), i())],
            premises: vec![Proof::Hyp("when".into())],
        },
        &[],
    )
}
