//! Facts about the builtins: equations stated directly over builtin calls
//! with untyped variables, each proved by steps from the wall rules.
//!
//! A law cites a fact by its key in `using` (`List.concat.assoc`), like a
//! law of its own program. A citation carries the fact's whole step proof
//! ([`super::LawRef::fact`]), and both checkers check that proof before
//! they let a step use the fact, so a fact is never an assumption. Lean
//! states each fact once, for every element type (`{α : Type}`), from the
//! same terms, and proves it with the same steps.
//!
//! The `List.` prefix of a `using` name is reserved for these facts: a
//! user module named `List` is already refused.

use crate::ast::{BinOp, Type};

use super::term::{self, Term, binop, builtin, var};
use super::{LawRef, Obligation, Proof, Script, WallRule};

/// One fact: its key in `using`, its Lean theorem name, and its script.
#[derive(Debug, Clone, PartialEq)]
pub struct Fact {
    pub key: &'static str,
    pub lean: &'static str,
    pub script: Script,
}

impl Fact {
    /// The fact as a law a script cites, with its proof.
    pub fn law_ref(&self) -> LawRef {
        let ob = &self.script.obligation;
        LawRef {
            key: self.key.to_string(),
            givens: ob.givens.clone(),
            premise: None,
            lhs: ob.lhs.clone(),
            rhs: ob.rhs.clone(),
            fact: Some(Box::new(self.script.clone())),
        }
    }
}

impl Fact {
    /// The statement as an Aver law claim: `lhs => rhs`.
    pub fn claim(&self) -> String {
        let ob = &self.script.obligation;
        let show = |t: &Term| super::show::term(t, &super::sexpr::BuiltinsOnly);
        format!("{} => {}", show(&ob.lhs), show(&ob.rhs))
    }

    /// The facts its proof cites.
    pub fn cites(&self) -> Vec<String> {
        self.script.laws.iter().map(|l| l.key.clone()).collect()
    }
}

/// The facts whose key starts with `prefix`, as Markdown: one entry per
/// fact with its statement as an Aver law. `docs/builtin-facts.md` is this
/// text for every fact.
pub fn markdown(prefix: &str) -> String {
    let mut out = String::from(
        "# Builtin facts\n\n<!-- Generated by `aver facts --markdown > docs/builtin-facts.md`; edit `src/ir/proof_steps/facts.rs`, not this file. -->\n\nA law cites a builtin fact by name in `using`, as it cites a law of its own program. Each fact holds for lists of every element type, so its givens have no element type here. The proof of each fact is written as steps and travels with every citation: the kernel written in Aver checks it before the law may use the fact, and Lean states the fact once, for every element type, and proves it with the same steps. When the steps stop at a term a fact's left side matches, `aver proof` names the fact in a hint. `aver facts` prints this list.\n",
    );
    for fact in all().iter().filter(|f| f.key.starts_with(prefix)) {
        out.push_str(&format!(
            "\n## `{}`\n\n```aver\ngiven {}\n{}\n```\n",
            fact.key,
            fact.script.obligation.givens.join(", "),
            fact.claim()
        ));
        let cites = fact.cites();
        if !cites.is_empty() {
            out.push_str(&format!(
                "\nProved from {}.\n",
                cites
                    .iter()
                    .map(|c| format!("`{c}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }
    out
}

/// Whether `name` is in the namespace reserved for facts.
pub fn is_fact_name(name: &str) -> bool {
    name.starts_with("List.")
}

pub fn named(key: &str) -> Option<Fact> {
    all().into_iter().find(|f| f.key == key)
}

/// Every fact, each after the facts its proof cites.
pub fn all() -> Vec<Fact> {
    vec![
        len_of_concat(),
        concat_assoc(),
        concat_right_identity(),
        len_nonneg(),
        take_of_concat(),
        drop_of_concat(),
        len_of_reverse(),
        reverse_of_concat(),
        reverse_involutive(),
    ]
}

fn len(l: Term) -> Term {
    builtin("List.len", vec![l], Some(Type::Int))
}

fn concat(a: Term, b: Term) -> Term {
    builtin("List.concat", vec![a, b], None)
}

fn cell(x: Term, t: Term) -> Term {
    builtin("List.prepend", vec![x, t], None)
}

fn add(a: Term, b: Term) -> Term {
    binop(BinOp::Add, a, b)
}

fn one() -> Term {
    term::int(&1.into())
}

fn rule(rule: WallRule, subst: Vec<(&str, Term)>) -> Proof {
    Proof::Rule {
        rule,
        subst: subst.into_iter().map(|(k, v)| (k.to_string(), v)).collect(),
        premises: Vec::new(),
    }
}

fn symm(p: Proof) -> Proof {
    Proof::Symm(Box::new(p))
}

fn congr(ctx: Term, inner: Proof) -> Proof {
    Proof::Congr {
        ctx,
        inner: Box::new(inner),
    }
}

fn trans(terms: Vec<Term>, steps: Vec<Proof>) -> Proof {
    Proof::Trans { terms, steps }
}

/// A fact over list givens, proved by induction on `on`; the cell case
/// names its parts `x` and `t` and its hypothesis `ih`.
#[allow(clippy::too_many_arguments)]
fn by_list_induction(
    key: &'static str,
    lean: &'static str,
    givens: &[&str],
    lhs: Term,
    rhs: Term,
    nil: Proof,
    cons: Proof,
    uses: &[Fact],
) -> Fact {
    let givens: Vec<String> = givens.iter().map(|g| g.to_string()).collect();
    Fact {
        key,
        lean,
        script: Script {
            obligation: Obligation {
                key: key.to_string(),
                givens: givens.clone(),
                finite: Vec::new(),
                lists: givens,
                premise: None,
                lhs: lhs.clone(),
                rhs: rhs.clone(),
            },
            defs: Vec::new(),
            consts: Vec::new(),
            laws: uses.iter().map(Fact::law_ref).collect(),
            proof: Proof::InductList {
                var: "a".into(),
                lhs,
                rhs,
                nil: Box::new(nil),
                head: "x".into(),
                tail: "t".into(),
                ih: "ih".into(),
                cons: Box::new(cons),
            },
        },
    }
}

/// `List.len(List.concat(a, b)) = List.len(a) + List.len(b)`.
fn len_of_concat() -> Fact {
    let (a, b, x, t) = (|| var("a"), || var("b"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = trans(
        vec![
            len(concat(nil(), b())),
            len(b()),
            add(term::int(&0.into()), len(b())),
            add(len(nil()), len(b())),
        ],
        vec![
            congr(
                len(term::hole()),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            symm(rule(WallRule::ZeroAdd, vec![("a", len(b()))])),
            congr(
                add(term::hole(), len(b())),
                symm(rule(WallRule::LenNil, vec![])),
            ),
        ],
    );
    let step = trans(
        vec![
            len(concat(cell(x(), t()), b())),
            len(cell(x(), concat(t(), b()))),
            add(len(concat(t(), b())), one()),
            add(add(len(t()), len(b())), one()),
            add(add(len(t()), one()), len(b())),
            add(len(cell(x(), t())), len(b())),
        ],
        vec![
            congr(
                len(term::hole()),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            rule(WallRule::LenCons, vec![("x", x()), ("a", concat(t(), b()))]),
            congr(add(term::hole(), one()), Proof::Hyp("ih".into())),
            Proof::Ring {
                lhs: add(add(len(t()), len(b())), one()),
                rhs: add(add(len(t()), one()), len(b())),
            },
            congr(
                add(term::hole(), len(b())),
                symm(rule(WallRule::LenCons, vec![("x", x()), ("a", t())])),
            ),
        ],
    );
    by_list_induction(
        "List.len.ofConcat",
        "list_len_ofConcat",
        &["a", "b"],
        len(concat(a(), b())),
        add(len(a()), len(b())),
        base,
        step,
        &[],
    )
}

/// `List.concat(List.concat(a, b), c) = List.concat(a, List.concat(b, c))`.
fn concat_assoc() -> Fact {
    let (a, b, c, x, t) = (
        || var("a"),
        || var("b"),
        || var("c"),
        || var("x"),
        || var("t"),
    );
    let nil = term::nil;
    let base = trans(
        vec![
            concat(concat(nil(), b()), c()),
            concat(b(), c()),
            concat(nil(), concat(b(), c())),
        ],
        vec![
            congr(
                concat(term::hole(), c()),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            symm(rule(WallRule::ConcatNil, vec![("b", concat(b(), c()))])),
        ],
    );
    let step = trans(
        vec![
            concat(concat(cell(x(), t()), b()), c()),
            concat(cell(x(), concat(t(), b())), c()),
            cell(x(), concat(concat(t(), b()), c())),
            cell(x(), concat(t(), concat(b(), c()))),
            concat(cell(x(), t()), concat(b(), c())),
        ],
        vec![
            congr(
                concat(term::hole(), c()),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            rule(
                WallRule::ConcatCons,
                vec![("x", x()), ("a", concat(t(), b())), ("b", c())],
            ),
            congr(cell(x(), term::hole()), Proof::Hyp("ih".into())),
            symm(rule(
                WallRule::ConcatCons,
                vec![("x", x()), ("a", t()), ("b", concat(b(), c()))],
            )),
        ],
    );
    by_list_induction(
        "List.concat.assoc",
        "list_concat_assoc",
        &["a", "b", "c"],
        concat(concat(a(), b()), c()),
        concat(a(), concat(b(), c())),
        base,
        step,
        &[],
    )
}

fn reverse(l: Term) -> Term {
    builtin("List.reverse", vec![l], None)
}

fn take(l: Term, n: Term) -> Term {
    builtin("List.take", vec![l, n], None)
}

fn drop(l: Term, n: Term) -> Term {
    builtin("List.drop", vec![l, n], None)
}

fn single(x: Term) -> Term {
    cell(x, term::nil())
}

fn zero() -> Term {
    term::int(&0.into())
}

/// An earlier fact at explicit arguments.
fn cite(fact: &Fact, args: Vec<Term>) -> Proof {
    Proof::Law {
        law: fact.key.to_string(),
        subst: fact
            .script
            .obligation
            .givens
            .iter()
            .cloned()
            .zip(args)
            .collect(),
        premise: None,
    }
}

/// `n > 0` decided `true` from `List.len(l) >= 0`: split on that
/// comparison, settle the goal linearly when it holds, and refute the other
/// case with `List.len.nonneg`.
fn positive_from_len(goal: Term, l: Term, h: &str) -> Proof {
    use super::linear;
    let known = binop(BinOp::Gte, len(l.clone()), zero());
    let mut atoms = Vec::new();
    let facts = vec![
        linear::as_nonneg(&goal, false, &mut atoms).expect("an Int comparison"),
        linear::as_nonneg(&known, true, &mut atoms).expect("an Int comparison"),
    ];
    let weights = linear::certificate(&facts).expect("the goal follows linearly");
    Proof::Cases {
        on: known.clone(),
        hyp: h.to_string(),
        if_true: Box::new(Proof::Linear {
            goal: goal.clone(),
            value: true,
            hyps: vec![h.to_string()],
            weights,
        }),
        if_false: Box::new(Proof::Absurd {
            contradiction: Box::new(trans(
                vec![term::boolean(true), known, term::boolean(false)],
                vec![
                    symm(cite(&len_nonneg(), vec![l])),
                    Proof::Hyp(h.to_string()),
                ],
            )),
            lhs: goal,
            rhs: term::boolean(true),
        }),
    }
}

/// `f(l, 0) = want` for every list `l`, by induction on `l`: `[]` by the
/// empty-list rule, a cell by the rule for a count at or below zero.
fn at_zero(
    f: fn(Term, Term) -> Term,
    l: &str,
    want: fn(Term) -> Term,
    nil_rule: WallRule,
    le_rule: WallRule,
) -> Proof {
    let (x, t) = (|| var("x2"), || var("t2"));
    Proof::InductList {
        var: l.to_string(),
        lhs: f(var(l), zero()),
        rhs: want(var(l)),
        nil: Box::new(rule(nil_rule, vec![("n", zero())])),
        head: "x2".into(),
        tail: "t2".into(),
        ih: "ih2".into(),
        cons: Box::new(Proof::Rule {
            rule: le_rule,
            subst: vec![("x".into(), x()), ("a".into(), t()), ("n".into(), zero())],
            premises: vec![Proof::Compute {
                lhs: binop(BinOp::Lte, zero(), zero()),
                rhs: term::boolean(true),
            }],
        }),
    }
}

/// `List.concat(a, []) = a`.
fn concat_right_identity() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nil = term::nil;
    by_list_induction(
        "List.concat.rightIdentity",
        "list_concat_rightIdentity",
        &["a"],
        concat(a(), nil()),
        a(),
        rule(WallRule::ConcatNil, vec![("b", nil())]),
        trans(
            vec![
                concat(cell(x(), t()), nil()),
                cell(x(), concat(t(), nil())),
                cell(x(), t()),
            ],
            vec![
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", nil())],
                ),
                congr(cell(x(), term::hole()), Proof::Hyp("ih".into())),
            ],
        ),
        &[],
    )
}

/// `List.len(a) >= 0` is `true`.
fn len_nonneg() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nonneg = |l: Term| binop(BinOp::Gte, l, zero());
    let goal = nonneg(add(len(t()), one()));
    let mut atoms = Vec::new();
    let weights = super::linear::certificate(&[
        super::linear::as_nonneg(&goal, false, &mut atoms).expect("comparison"),
        super::linear::as_nonneg(&nonneg(len(t())), true, &mut atoms).expect("comparison"),
    ])
    .expect("linear");
    by_list_induction(
        "List.len.nonneg",
        "list_len_nonneg",
        &["a"],
        nonneg(len(a())),
        term::boolean(true),
        // Through `0 >= 0`: Lean decides only a closed statement, and an
        // empty list of some element type is not one.
        trans(
            vec![
                nonneg(len(term::nil())),
                nonneg(zero()),
                term::boolean(true),
            ],
            vec![
                congr(nonneg(term::hole()), rule(WallRule::LenNil, vec![])),
                Proof::Compute {
                    lhs: nonneg(zero()),
                    rhs: term::boolean(true),
                },
            ],
        ),
        trans(
            vec![
                nonneg(len(cell(x(), t()))),
                goal.clone(),
                term::boolean(true),
            ],
            vec![
                congr(
                    nonneg(term::hole()),
                    rule(WallRule::LenCons, vec![("x", x()), ("a", t())]),
                ),
                Proof::Linear {
                    goal,
                    value: true,
                    hyps: vec!["ih".into()],
                    weights,
                },
            ],
        ),
        &[],
    )
}

/// The cell case shared by `take` and `drop` of a concatenation at the
/// length of its first part: open the cell, step past it, then the
/// hypothesis.
fn sliced_cell(
    slice: fn(Term, Term) -> Term,
    gt_rule: WallRule,
    after: fn(Term, Term) -> Term,
    result: Term,
) -> Proof {
    let (b, x, t) = (|| var("b"), || var("x"), || var("t"));
    let n1 = || add(len(t()), one());
    let ctb = || concat(t(), b());
    trans(
        vec![
            slice(concat(cell(x(), t()), b()), len(cell(x(), t()))),
            slice(cell(x(), ctb()), len(cell(x(), t()))),
            slice(cell(x(), ctb()), n1()),
            after(x(), slice(ctb(), binop(BinOp::Sub, n1(), one()))),
            after(x(), slice(ctb(), len(t()))),
            after(x(), result),
        ],
        vec![
            congr(
                slice(term::hole(), len(cell(x(), t()))),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            congr(
                slice(cell(x(), ctb()), term::hole()),
                rule(WallRule::LenCons, vec![("x", x()), ("a", t())]),
            ),
            Proof::Rule {
                rule: gt_rule,
                subst: vec![("x".into(), x()), ("a".into(), ctb()), ("n".into(), n1())],
                premises: vec![positive_from_len(
                    binop(BinOp::Gt, n1(), zero()),
                    t(),
                    "h_len",
                )],
            },
            congr(
                after(x(), slice(ctb(), term::hole())),
                Proof::Ring {
                    lhs: binop(BinOp::Sub, n1(), one()),
                    rhs: len(t()),
                },
            ),
            congr(after(x(), term::hole()), Proof::Hyp("ih".into())),
        ],
    )
}

/// `List.take(List.concat(a, b), List.len(a)) = a`.
fn take_of_concat() -> Fact {
    let (a, b) = (|| var("a"), || var("b"));
    let nil = term::nil;
    let base = trans(
        vec![
            take(concat(nil(), b()), len(nil())),
            take(b(), len(nil())),
            take(b(), zero()),
            nil(),
        ],
        vec![
            congr(
                take(term::hole(), len(nil())),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            congr(take(b(), term::hole()), rule(WallRule::LenNil, vec![])),
            at_zero(
                take,
                "b",
                |_| term::nil(),
                WallRule::TakeNil,
                WallRule::TakeConsLe,
            ),
        ],
    );
    by_list_induction(
        "List.take.ofConcat",
        "list_take_ofConcat",
        &["a", "b"],
        take(concat(a(), b()), len(a())),
        a(),
        base,
        sliced_cell(take, WallRule::TakeConsGt, cell, var("t")),
        &[len_nonneg()],
    )
}

/// `List.drop(List.concat(a, b), List.len(a)) = b`.
fn drop_of_concat() -> Fact {
    let (a, b) = (|| var("a"), || var("b"));
    let nil = term::nil;
    let base = trans(
        vec![
            drop(concat(nil(), b()), len(nil())),
            drop(b(), len(nil())),
            drop(b(), zero()),
            b(),
        ],
        vec![
            congr(
                drop(term::hole(), len(nil())),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            congr(drop(b(), term::hole()), rule(WallRule::LenNil, vec![])),
            at_zero(drop, "b", |l| l, WallRule::DropNil, WallRule::DropConsLe),
        ],
    );
    by_list_induction(
        "List.drop.ofConcat",
        "list_drop_ofConcat",
        &["a", "b"],
        drop(concat(a(), b()), len(a())),
        b(),
        base,
        sliced_cell(drop, WallRule::DropConsGt, |_, rest| rest, b()),
        &[len_nonneg()],
    )
}

/// `List.len(List.reverse(a)) = List.len(a)`.
fn len_of_reverse() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = congr(len(term::hole()), rule(WallRule::ReverseNil, vec![]));
    let step = trans(
        vec![
            len(reverse(cell(x(), t()))),
            len(concat(reverse(t()), single(x()))),
            add(len(reverse(t())), len(single(x()))),
            add(len(t()), len(single(x()))),
            add(len(t()), add(len(nil()), one())),
            add(len(t()), add(zero(), one())),
            add(len(t()), one()),
            len(cell(x(), t())),
        ],
        vec![
            congr(
                len(term::hole()),
                rule(WallRule::ReverseCons, vec![("x", x()), ("a", t())]),
            ),
            cite(&len_of_concat(), vec![reverse(t()), single(x())]),
            congr(add(term::hole(), len(single(x()))), Proof::Hyp("ih".into())),
            congr(
                add(len(t()), term::hole()),
                rule(WallRule::LenCons, vec![("x", x()), ("a", nil())]),
            ),
            congr(
                add(len(t()), add(term::hole(), one())),
                rule(WallRule::LenNil, vec![]),
            ),
            Proof::Ring {
                lhs: add(len(t()), add(zero(), one())),
                rhs: add(len(t()), one()),
            },
            symm(rule(WallRule::LenCons, vec![("x", x()), ("a", t())])),
        ],
    );
    by_list_induction(
        "List.len.ofReverse",
        "list_len_ofReverse",
        &["a"],
        len(reverse(a())),
        len(a()),
        base,
        step,
        &[len_of_concat()],
    )
}

/// `List.reverse(List.concat(a, b)) = List.concat(List.reverse(b), List.reverse(a))`.
fn reverse_of_concat() -> Fact {
    let (a, b, x, t) = (|| var("a"), || var("b"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = trans(
        vec![
            reverse(concat(nil(), b())),
            reverse(b()),
            concat(reverse(b()), nil()),
            concat(reverse(b()), reverse(nil())),
        ],
        vec![
            congr(
                reverse(term::hole()),
                rule(WallRule::ConcatNil, vec![("b", b())]),
            ),
            symm(cite(&concat_right_identity(), vec![reverse(b())])),
            congr(
                concat(reverse(b()), term::hole()),
                symm(rule(WallRule::ReverseNil, vec![])),
            ),
        ],
    );
    let step = trans(
        vec![
            reverse(concat(cell(x(), t()), b())),
            reverse(cell(x(), concat(t(), b()))),
            concat(reverse(concat(t(), b())), single(x())),
            concat(concat(reverse(b()), reverse(t())), single(x())),
            concat(reverse(b()), concat(reverse(t()), single(x()))),
            concat(reverse(b()), reverse(cell(x(), t()))),
        ],
        vec![
            congr(
                reverse(term::hole()),
                rule(
                    WallRule::ConcatCons,
                    vec![("x", x()), ("a", t()), ("b", b())],
                ),
            ),
            rule(
                WallRule::ReverseCons,
                vec![("x", x()), ("a", concat(t(), b()))],
            ),
            congr(concat(term::hole(), single(x())), Proof::Hyp("ih".into())),
            cite(
                &concat_assoc(),
                vec![reverse(b()), reverse(t()), single(x())],
            ),
            congr(
                concat(reverse(b()), term::hole()),
                symm(rule(WallRule::ReverseCons, vec![("x", x()), ("a", t())])),
            ),
        ],
    );
    by_list_induction(
        "List.reverse.ofConcat",
        "list_reverse_ofConcat",
        &["a", "b"],
        reverse(concat(a(), b())),
        concat(reverse(b()), reverse(a())),
        base,
        step,
        &[concat_assoc(), concat_right_identity()],
    )
}

/// `List.reverse(List.reverse(a)) = a`.
fn reverse_involutive() -> Fact {
    let (a, x, t) = (|| var("a"), || var("x"), || var("t"));
    let nil = term::nil;
    let base = trans(
        vec![reverse(reverse(nil())), reverse(nil()), nil()],
        vec![
            congr(reverse(term::hole()), rule(WallRule::ReverseNil, vec![])),
            rule(WallRule::ReverseNil, vec![]),
        ],
    );
    let step = trans(
        vec![
            reverse(reverse(cell(x(), t()))),
            reverse(concat(reverse(t()), single(x()))),
            concat(reverse(single(x())), reverse(reverse(t()))),
            concat(reverse(single(x())), t()),
            concat(concat(reverse(nil()), single(x())), t()),
            concat(concat(nil(), single(x())), t()),
            concat(single(x()), t()),
            cell(x(), concat(nil(), t())),
            cell(x(), t()),
        ],
        vec![
            congr(
                reverse(term::hole()),
                rule(WallRule::ReverseCons, vec![("x", x()), ("a", t())]),
            ),
            cite(&reverse_of_concat(), vec![reverse(t()), single(x())]),
            congr(
                concat(reverse(single(x())), term::hole()),
                Proof::Hyp("ih".into()),
            ),
            congr(
                concat(term::hole(), t()),
                rule(WallRule::ReverseCons, vec![("x", x()), ("a", nil())]),
            ),
            congr(
                concat(concat(term::hole(), single(x())), t()),
                rule(WallRule::ReverseNil, vec![]),
            ),
            congr(
                concat(term::hole(), t()),
                rule(WallRule::ConcatNil, vec![("b", single(x()))]),
            ),
            rule(
                WallRule::ConcatCons,
                vec![("x", x()), ("a", nil()), ("b", t())],
            ),
            congr(
                cell(x(), term::hole()),
                rule(WallRule::ConcatNil, vec![("b", t())]),
            ),
        ],
    );
    by_list_induction(
        "List.reverse.involutive",
        "list_reverse_involutive",
        &["a"],
        reverse(reverse(a())),
        a(),
        base,
        step,
        &[reverse_of_concat()],
    )
}
