//! Build-time Cargo provenance for projects generated by Aver.
//!
//! `cargo install --path`, `cargo install --git`, and registry installation
//! are different dependency graphs. The compiler records which graph built it
//! in `build.rs`; every generated Cargo manifest then reuses that exact source
//! for Aver-owned crates. This keeps the generated runtime and cached provider
//! host on one revision instead of pairing git code with a same-version but
//! older registry package.

use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ToolchainSource {
    Path { root: String },
    Git { url: String, rev: String },
    Registry,
}

impl ToolchainSource {
    pub(crate) fn current() -> Self {
        match env!("AVER_BUILD_SOURCE_KIND") {
            "path" => Self::Path {
                root: env!("AVER_BUILD_SOURCE_PATH").to_string(),
            },
            "git" => Self::Git {
                url: env!("AVER_BUILD_GIT_URL").to_string(),
                rev: env!("AVER_BUILD_GIT_REV").to_string(),
            },
            "registry" => Self::Registry,
            kind => panic!("unsupported embedded Aver build source '{kind}'"),
        }
    }

    /// Local checkout root when this binary was path-built. Git and registry
    /// sources are immutable Cargo identities and need no source-tree stamp.
    pub(crate) fn local_root(&self) -> Option<&Path> {
        match self {
            Self::Path { root } => Some(Path::new(root)),
            Self::Git { .. } | Self::Registry => None,
        }
    }

    pub(crate) fn aver_lang_dependency(&self, version: &str, features: &[&str]) -> String {
        self.dependency_line("aver", Some("aver-lang"), version, features, None)
    }

    pub(crate) fn aver_rt_dependency(&self, version: &str, features: &[&str]) -> String {
        self.dependency_line("aver-rt", None, version, features, Some("aver-rt"))
    }

    pub(crate) fn exact_path_dependency(
        alias: &str,
        package: Option<&str>,
        version: &str,
        features: &[&str],
        path: &str,
    ) -> String {
        Self::Path {
            root: path.replace('\\', "/"),
        }
        .dependency_line(alias, package, version, features, None)
    }

    fn dependency_line(
        &self,
        alias: &str,
        package: Option<&str>,
        version: &str,
        features: &[&str],
        path_suffix: Option<&str>,
    ) -> String {
        let mut fields = Vec::new();
        if let Some(package) = package {
            fields.push(format!("package = {}", toml_string(package)));
        }
        match self {
            Self::Path { root } => {
                let mut path = PathBuf::from(root);
                if let Some(suffix) = path_suffix {
                    path.push(suffix);
                }
                fields.push(format!(
                    "path = {}",
                    toml_string(&path.to_string_lossy().replace('\\', "/"))
                ));
            }
            Self::Git { url, rev } => {
                fields.push(format!("git = {}", toml_string(url)));
                fields.push(format!("rev = {}", toml_string(rev)));
            }
            Self::Registry => {}
        }
        fields.push(format!("version = {}", toml_string(version)));
        if !features.is_empty() {
            fields.push(format!(
                "features = [{}]",
                features
                    .iter()
                    .map(|feature| toml_string(feature))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        format!("{alias} = {{ {} }}", fields.join(", "))
    }
}

fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            ch if ch <= '\u{001f}' => {
                use std::fmt::Write;
                write!(out, "\\u{:04X}", ch as u32).expect("write to String");
            }
            ch => out.push(ch),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::ToolchainSource;

    #[test]
    fn path_source_routes_each_aver_package_inside_one_checkout() {
        let source = ToolchainSource::Path {
            root: "/work/aver".to_string(),
        };
        assert_eq!(
            source.aver_lang_dependency("=0.29.0-dev", &[]),
            "aver = { package = \"aver-lang\", path = \"/work/aver\", version = \"=0.29.0-dev\" }"
        );
        assert_eq!(
            source.aver_rt_dependency("=0.4.10", &["http"]),
            "aver-rt = { path = \"/work/aver/aver-rt\", version = \"=0.4.10\", features = [\"http\"] }"
        );
    }

    #[test]
    fn git_source_pins_every_aver_package_to_the_build_revision() {
        let source = ToolchainSource::Git {
            url: "https://github.com/jasisz/aver".to_string(),
            rev: "ea1bfa56".to_string(),
        };
        assert_eq!(
            source.aver_lang_dependency("=0.29.0-dev", &["wasip2"]),
            "aver = { package = \"aver-lang\", git = \"https://github.com/jasisz/aver\", rev = \"ea1bfa56\", version = \"=0.29.0-dev\", features = [\"wasip2\"] }"
        );
        assert_eq!(
            source.aver_rt_dependency("=0.4.10", &[]),
            "aver-rt = { git = \"https://github.com/jasisz/aver\", rev = \"ea1bfa56\", version = \"=0.4.10\" }"
        );
    }

    #[test]
    fn registry_source_keeps_exact_versions() {
        let source = ToolchainSource::Registry;
        assert_eq!(
            source.aver_rt_dependency("=0.4.10", &["random"]),
            "aver-rt = { version = \"=0.4.10\", features = [\"random\"] }"
        );
    }
}
